local name, addon = ...

addon.action_labels = {
    --Movement Keys
    MOVEANDSTEER = "Move and Steer",
    MOVEFORWARD = "Move Forward",
    MOVEBACKWARD = "Move Backward",
    TURNLEFT = "Turn Left",
    TURNRIGHT = "Turn Right",
    STRAFELEFT = "Strafe Left",
    STRAFERIGHT = "Strafe Right",
    JUMP = "Jump",
    SITORSTAND = "Sit/Move Down",
    TOGGLESHEATH = "Sheath/Unsheath Weapon",
    TOGGLEAUTORUN = "Toggle Autorun",
    STARTAUTORUN = "Start Autorun",
    STOPAUTORUN = "Stop Autorun",
    PITCHUP = "Pitch Up",
    PITCHDOWN = "Pitch Down",
    TOGGLERUN = "Toggle Run/Walk",
    FOLLOWTARGET = "Follow Target",

    --Action Bar
    ACTIONBUTTON1 = "Action Button 1",
    ACTIONBUTTON2 = "Action Button 2",
    ACTIONBUTTON3 = "Action Button 3",
    ACTIONBUTTON4 = "Action Button 4",
    ACTIONBUTTON5 = "Action Button 5",
    ACTIONBUTTON6 = "Action Button 6",
    ACTIONBUTTON7 = "Action Button 7",
    ACTIONBUTTON8 = "Action Button 8",
    ACTIONBUTTON9 = "Action Button 9",
    ACTIONBUTTON10 = "Action Button 10",
    ACTIONBUTTON11 = "Action Button 11",
    ACTIONBUTTON12 = "Action Button 12",

    EXTRAACTIONBUTTON1 = "Extra Action Button 1",

    BONUSACTIONBUTTON1 = "Pet Action Button 1",
    BONUSACTIONBUTTON2 = "Pet Action Button 2",
    BONUSACTIONBUTTON3 = "Pet Action Button 3",
    BONUSACTIONBUTTON4 = "Pet Action Button 4",
    BONUSACTIONBUTTON5 = "Pet Action Button 5",
    BONUSACTIONBUTTON6 = "Pet Action Button 6",
    BONUSACTIONBUTTON7 = "Pet Action Button 7",
    BONUSACTIONBUTTON8 = "Pet Action Button 8",
    BONUSACTIONBUTTON9 = "Pet Action Button 9",
    BONUSACTIONBUTTON10 = "Pet Action Button 10",

    ACTIONPAGE1 = "Action Page 1",
    ACTIONPAGE2 = "Action Page 2",
    ACTIONPAGE3 = "Action Page 3",
    ACTIONPAGE4 = "Action Page 4",
    ACTIONPAGE5 = "Action Page 5",
    ACTIONPAGE6 = "Action Page 6",

    PREVIOUSACTIONPAGE = "Previous Action Bar",
    NEXTACTIONPAGE = "Next Action Bar",
    TOGGLEACTIONBARLOCK = "Toggle Action Bar Lock",
    TOGGLEAUTOSELFCAST = "Toggle Self Cast",

    SHAPESHIFTBUTTON1 = "Special Action Button 1",
    SHAPESHIFTBUTTON2 = "Special Action Button 2",
    SHAPESHIFTBUTTON3 = "Special Action Button 3",
    SHAPESHIFTBUTTON4 = "Special Action Button 4",
    SHAPESHIFTBUTTON5 = "Special Action Button 5",
    SHAPESHIFTBUTTON6 = "Special Action Button 6",
    SHAPESHIFTBUTTON7 = "Special Action Button 7",
    SHAPESHIFTBUTTON8 = "Special Action Button 8",
    SHAPESHIFTBUTTON9 = "Special Action Button 9",
    SHAPESHIFTBUTTON10 = "Special Action Button 10",

    --Action Bar 2
    MULTIACTIONBAR1BUTTON1 = "Action Bar 2 Button 1",
    MULTIACTIONBAR1BUTTON2 = "Action Bar 2 Button 2",
    MULTIACTIONBAR1BUTTON3 = "Action Bar 2 Button 3",
    MULTIACTIONBAR1BUTTON4 = "Action Bar 2 Button 4",
    MULTIACTIONBAR1BUTTON5 = "Action Bar 2 Button 5",
    MULTIACTIONBAR1BUTTON6 = "Action Bar 2 Button 6",
    MULTIACTIONBAR1BUTTON7 = "Action Bar 2 Button 7",
    MULTIACTIONBAR1BUTTON8 = "Action Bar 2 Button 8",
    MULTIACTIONBAR1BUTTON9 = "Action Bar 2 Button 9",
    MULTIACTIONBAR1BUTTON10 = "Action Bar 2 Button 10",
    MULTIACTIONBAR1BUTTON11 = "Action Bar 2 Button 11",
    MULTIACTIONBAR1BUTTON12 = "Action Bar 2 Button 12",

    --Action Bar 3
    MULTIACTIONBAR2BUTTON1 = "Action Bar 3 Button 1",
    MULTIACTIONBAR2BUTTON2 = "Action Bar 3 Button 2",
    MULTIACTIONBAR2BUTTON3 = "Action Bar 3 Button 3",
    MULTIACTIONBAR2BUTTON4 = "Action Bar 3 Button 4",
    MULTIACTIONBAR2BUTTON5 = "Action Bar 3 Button 5",
    MULTIACTIONBAR2BUTTON6 = "Action Bar 3 Button 6",
    MULTIACTIONBAR2BUTTON7 = "Action Bar 3 Button 7",
    MULTIACTIONBAR2BUTTON8 = "Action Bar 3 Button 8",
    MULTIACTIONBAR2BUTTON9 = "Action Bar 3 Button 9",
    MULTIACTIONBAR2BUTTON10 = "Action Bar 3 Button 10",
    MULTIACTIONBAR2BUTTON11 = "Action Bar 3 Button 11",
    MULTIACTIONBAR2BUTTON12 = "Action Bar 3 Button 12",

    --Action Bar 4
    MULTIACTIONBAR3BUTTON1 = "Action Bar 4 Button 1",
    MULTIACTIONBAR3BUTTON2 = "Action Bar 4 Button 2",
    MULTIACTIONBAR3BUTTON3 = "Action Bar 4 Button 3",
    MULTIACTIONBAR3BUTTON4 = "Action Bar 4 Button 4",
    MULTIACTIONBAR3BUTTON5 = "Action Bar 4 Button 5",
    MULTIACTIONBAR3BUTTON6 = "Action Bar 4 Button 6",
    MULTIACTIONBAR3BUTTON7 = "Action Bar 4 Button 7",
    MULTIACTIONBAR3BUTTON8 = "Action Bar 4 Button 8",
    MULTIACTIONBAR3BUTTON9 = "Action Bar 4 Button 9",
    MULTIACTIONBAR3BUTTON10 = "Action Bar 4 Button 10",
    MULTIACTIONBAR3BUTTON11 = "Action Bar 4 Button 11",
    MULTIACTIONBAR3BUTTON12 = "Action Bar 4 Button 12",

    --Action Bar 5
    MULTIACTIONBAR4BUTTON1 = "Action Bar 5 Button 1",
    MULTIACTIONBAR4BUTTON2 = "Action Bar 5 Button 2",
    MULTIACTIONBAR4BUTTON3 = "Action Bar 5 Button 3",
    MULTIACTIONBAR4BUTTON4 = "Action Bar 5 Button 4",
    MULTIACTIONBAR4BUTTON5 = "Action Bar 5 Button 5",
    MULTIACTIONBAR4BUTTON6 = "Action Bar 5 Button 6",
    MULTIACTIONBAR4BUTTON7 = "Action Bar 5 Button 7",
    MULTIACTIONBAR4BUTTON8 = "Action Bar 5 Button 8",
    MULTIACTIONBAR4BUTTON9 = "Action Bar 5 Button 9",
    MULTIACTIONBAR4BUTTON10 = "Action Bar 5 Button 10",
    MULTIACTIONBAR4BUTTON11 = "Action Bar 5 Button 11",
    MULTIACTIONBAR4BUTTON12 = "Action Bar 5 Button 12",

    --Action Bar 6
    MULTIACTIONBAR5BUTTON1 = "Action Bar 6 Button 1",
    MULTIACTIONBAR5BUTTON2 = "Action Bar 6 Button 2",
    MULTIACTIONBAR5BUTTON3 = "Action Bar 6 Button 3",
    MULTIACTIONBAR5BUTTON4 = "Action Bar 6 Button 4",
    MULTIACTIONBAR5BUTTON5 = "Action Bar 6 Button 5",
    MULTIACTIONBAR5BUTTON6 = "Action Bar 6 Button 6",
    MULTIACTIONBAR5BUTTON7 = "Action Bar 6 Button 7",
    MULTIACTIONBAR5BUTTON8 = "Action Bar 6 Button 8",
    MULTIACTIONBAR5BUTTON9 = "Action Bar 6 Button 9",
    MULTIACTIONBAR5BUTTON10 = "Action Bar 6 Button 10",
    MULTIACTIONBAR5BUTTON11 = "Action Bar 6 Button 11",
    MULTIACTIONBAR5BUTTON12 = "Action Bar 6 Button 12",

    --Action Bar 7
    MULTIACTIONBAR6BUTTON1 = "Action Bar 7 Button 1",
    MULTIACTIONBAR6BUTTON2 = "Action Bar 7 Button 2",
    MULTIACTIONBAR6BUTTON3 = "Action Bar 7 Button 3",
    MULTIACTIONBAR6BUTTON4 = "Action Bar 7 Button 4",
    MULTIACTIONBAR6BUTTON5 = "Action Bar 7 Button 5",
    MULTIACTIONBAR6BUTTON6 = "Action Bar 7 Button 6",
    MULTIACTIONBAR6BUTTON7 = "Action Bar 7 Button 7",
    MULTIACTIONBAR6BUTTON8 = "Action Bar 7 Button 8",
    MULTIACTIONBAR6BUTTON9 = "Action Bar 7 Button 9",
    MULTIACTIONBAR6BUTTON10 = "Action Bar 7 Button 10",
    MULTIACTIONBAR6BUTTON11 = "Action Bar 7 Button 11",
    MULTIACTIONBAR6BUTTON12 = "Action Bar 7 Button 12",

    --Action Bar 8
    MULTIACTIONBAR7BUTTON1 = "Action Bar 8 Button 1",
    MULTIACTIONBAR7BUTTON2 = "Action Bar 8 Button 2",
    MULTIACTIONBAR7BUTTON3 = "Action Bar 8 Button 3",
    MULTIACTIONBAR7BUTTON4 = "Action Bar 8 Button 4",
    MULTIACTIONBAR7BUTTON5 = "Action Bar 8 Button 5",
    MULTIACTIONBAR7BUTTON6 = "Action Bar 8 Button 6",
    MULTIACTIONBAR7BUTTON7 = "Action Bar 8 Button 7",
    MULTIACTIONBAR7BUTTON8 = "Action Bar 8 Button 8",
    MULTIACTIONBAR7BUTTON9 = "Action Bar 8 Button 9",
    MULTIACTIONBAR7BUTTON10 = "Action Bar 8 Button 10",
    MULTIACTIONBAR7BUTTON11 = "Action Bar 8 Button 11",
    MULTIACTIONBAR7BUTTON12 = "Action Bar 8 Button 12",

    --Interface Panel
    TOGGLEGAMEMENU = "Toggle Game Menu",
    TOGGLEBACKPACK = "Toggle Backpack",
    TOGGLEREAGENTBAG1 = "Toggle Reagent Bag",
    TOGGLEBAG1 = "Toggle Bag 1",
    TOGGLEBAG2 = "Toggle Bag 2",
    TOGGLEBAG3 = "Toggle Bag 3",
    TOGGLEBAG4 = "Toggle Bag 4",
    OPENALLBAGS = "Open All Bags",

    TOGGLECHARACTER0 = "Toggle Character Pane",
    TOGGLECHARACTER2 = "Toggle Reputation Pane",
    TOGGLECURRENCY = "Toggle Currency Frame",

    TOGGLESPELLBOOK = "Toggle Spellbook",
    TOGGLEPROFESSIONBOOK = "Toggle Profession Book",
    TOGGLEPETBOOK = "Toggle Pet Book",
    TOGGLETALENTS = "Toggle Talent Pane",

    TOGGLEACHIEVEMENT = "Toggle Achievement Frame",
    TOGGLESTATISTICS = "Toggle Statistics Frame",

    TOGGLEQUESTLOG = "Toggle Quest Log",
    TOGGLEWORLDMAP = "Toggle World Map Pane",
    TOGGLEWORLDMAPSIZE = "Toggle World Map Size",
    TOGGLEMINIMAP = "Toggle Minimap",
    TOGGLEBATTLEFIELDMINIMAP = "Toggle Zone Map",
    TOGGLEWORLDSTATESCORES = "Toggle Score Screen",

    TOGGLEGUILDTAB = "Toggle Guild Pane",
    TOGGLESOCIAL = "Toggle Social Pane",
    TOGGLEFRIENDSTAB = "Toggle Friends Pane",
    TOGGLEQUICKJOINTAB = "Toggle Quick Join",
    TOGGLEWHOTAB = "Toggle Who Pane",
    TOGGLECHATTAB = "Toggle Chat Pane",
    TOGGLERAIDTAB = "Toggle Raid Pane",
    TOGGLETEXTTOSPEECH = "Toggle Text To Speech Config",

    TOGGLEGROUPFINDER = "Toggle Group Finder",
    TOGGLEDUNGEONSANDRAIDS = "Toggle Dungeons & Raids",
    TOGGLECHARACTER4 = "Toggle PVP Pane",

    TOGGLECOLLECTIONS = "Toggle Collections",
    TOGGLECOLLECTIONSMOUNTJOURNAL = "Toggle Mount Journal",
    TOGGLECOLLECTIONSPETJOURNAL = "Toggle Pet Journal",
    TOGGLECOLLECTIONSTOYBOX = "Toggle Toy Box",
    TOGGLECOLLECTIONSHEIRLOOM = "Toggle Heirlooms Pane",
    TOGGLECOLLECTIONSWARDROBE = "Toggle Appearances",

    TOGGLEENCOUNTERJOURNAL = "Toggle Adventure Guide",
    TOGGLEGARRISONLANDINGPAGE = "Toggle Garrison Report",

    --Chat
    OPENCHAT = "Open Chat",
    OPENCHATSLASH = "Open Chat Slash",
    CHATPAGEUP = "Chat Page Up",
    CHATPAGEDOWN = "Chat Page Down",
    CHATBOTTOM = "Chat Bottom",
    REPLY = "Chat Reply",
    REPLY2 = "Re-Whisper",
    COMBATLOGPAGEUP = "Combat Log Page Up",
    COMBATLOGPAGEDOWN = "Combat Log Page Down",
    COMBATLOGBOTTOM = "Combat Log Bottom",
    TOGGLECOMBATLOG = "Toggle Combat Log",
    TOGGLE_VOICE_SELF_MUTE = "Voice Chat: Toggle Mute Self",
    TOGGLE_VOICE_SELF_DEAFEN = "Voice Chat: Toggle Deafen Self",
    --MISSING-- = "Voice Chat: Push to Talk"
    TEXT_TO_SPEECH_STOP = "Stop Text To Speech Playback",

    --Targeting
    TARGETNEARESTENEMY = "Target Nearest Enemy",
    TARGETPREVIOUSENEMY = "Target Previous Enemy",
    TARGETSCANENEMY = "Target Scan Enemy (Hold)",
    TARGETNEARESTFRIEND = "Target Nearest Friend",
    TARGETPREVIOUSFRIEND = "Target Previous Friend",
    TARGETNEARESTENEMYPLAYER = "Target Nearest Enemy Player",
    TARGETPREVIOUSENEMYPLAYER = "Target Previous Enemy Player",
    TARGETNEARESTFRIENDPLAYER = "Target Nearest Friendly Player",
    TARGETPREVIOUSFRIENDPLAYER = "Target Previous Friendly Player",
    TARGETSELF = "Target Self",
    TARGETPARTYMEMBER1 = "Target Party Member 1",
    TARGETPARTYMEMBER2 = "Target Party Member 2",
    TARGETPARTYMEMBER3 = "Target Party Member 3",
    TARGETPARTYMEMBER4 = "Target Party Member 4",
    TARGETPET = "Target Pet",
    TARGETPARTYPET1 = "Target Party Pet 1",
    TARGETPARTYPET2 = "Target Party Pet 2",
    TARGETPARTYPET3 = "Target Party Pet 3",
    TARGETPARTYPET4 = "Target Party Pet 4",
    TARGETLASTHOSTILE = "Target Last Hostile",
    TARGETLASTTARGET = "Target Last Target",
    TARGETARENA1 = "Target Arena Enemy 1",
    TARGETARENA2 = "Target Arena Enemy 2",
    TARGETARENA3 = "Target Arena Enemy 3",
    TARGETARENA4 = "Target Arena Enemy 4",
    TARGETARENA5 = "Target Arena Enemy 5",
    FOCUSARENA1 = "Focus Arena Enemy 1",
    FOCUSARENA2 = "Focus Arena Enemy 2",
    FOCUSARENA3 = "Focus Arena Enemy 3",
    FOCUSARENA4 = "Focus Arena Enemy 4",
    FOCUSARENA5 = "Focus Arena Enemy 5",
    NAMEPLATES = "Show Enemy Nameplates",
    FRIENDNAMEPLATES = "Show Friendly Nameplates",
    ALLNAMEPLATES = "Show All Nameplates",
    INTERACTMOUSEOVER = "Interact With Mouseover",
    INTERACTTARGET = "Interact With Target",
    ASSISTTARGET = "Assist Target",
    ATTACKTARGET = "Attack Target",
    STARTATTACK = "Start Attack",
    PETATTACK = "Pet Attack",
    FOCUSTARGET = "Focus Target",
    TARGETFOCUS = "Target Focus",
    TARGETMOUSEOVER = "Target Mouseover",
    TARGETTALKER = "Target Current Talker",

    --Target Markers
    RAIDTARGET1 = "Assign Star to Target",
    RAIDTARGET2 = "Assign Circle to Target",
    RAIDTARGET3 = "Assign Diamond to Target",
    RAIDTARGET4 = "Assign Triangle to Target",
    RAIDTARGET5 = "Assign Moon to Target",
    RAIDTARGET6 = "Assign Square to Target",
    RAIDTARGET7 = "Assign Cross to Target",
    RAIDTARGET8 = "Assign Skull to Target",
    RAIDTARGETNONE = "Clear Target Marker Icon",

    --Vehicle Controls
    VEHICLEEXIT = "Exit Vehicle",
    VEHICLEPREVSEAT = "Previous Seat",
    VEHICLENEXTSEAT = "Next Seat",
    VEHICLEAIMUP = "Aim Up",
    VEHICLEAIMDOWN = "Aim Down",
    VEHICLEAIMINCREMENT = "Aim Increment",
    VEHICLEAIMDECREMENT = "Aim Decrement",

    --Camera
    NEXTVIEW = "Next View",
    PREVVIEW = "Previous View",
    CAMERAZOOMIN = "Zoom In",
    CAMERAZOOMOUT = "Zoom Out",
    SETVIEW1 = "Set View 1",
    SETVIEW2 = "Set View 2",
    SETVIEW3 = "Set View 3",
    SETVIEW4 = "Set View 4",
    SETVIEW5 = "Set View 5",
    SAVEVIEW1 = "Save View 1",
    SAVEVIEW2 = "Save View 2",
    SAVEVIEW3 = "Save View 3",
    SAVEVIEW4 = "Save View 4",
    SAVEVIEW5 = "Save View 5",
    RESETVIEW1 = "Reset View 1",
    RESETVIEW2 = "Reset View 2",
    RESETVIEW3 = "Reset View 3",
    RESETVIEW4 = "Reset View 4",
    RESETVIEW5 = "Reset View 5",
    FLIPCAMERAYAW = "Flip Camera",
    CENTERCAMERA = "Center Camera",

    --Ping System
    TOGGLEPINGLISTENER = "Ping",
    PINGATTACK = "Attack",
    PINGWARNING = "Warning",
    PINGONMYWAY = "On My Way",
    PINGASSIST = "Assist",

    --Miscellaneous
    STOPCASTING = "Stop Casting",
    STOPATTACK = "Stop Attacking",
    DISMOUNT = "Dismount",
    MINIMAPZOOMIN = "Minimap Zoom In",
    MINIMAPZOOMOUT = "Minimap Zoom Out",
    TOGGLEMUSIC = "Toggle Music",
    TOGGLESOUND = "Toggle Sound",
    MASTERVOLUMEUP = "Master Volume Up",
    MASTERVOLUMEDOWN = "Master Volume Down",
    TOGGLEUI = "Toggle User Interface",
    TOGGLEFPS = "Toggle Framerate Display",
    SCREENSHOT = "Screen Shot",
    ITEMCOMPARISONCYCLING = "Item Comparison Cycling",
    TOGGLEGRAPHICSSETTINGS = "Toggle Graphics Settings",
    TOGGLESELFHIGHLIGHT = "Toggle Self Highlight",
    TOGGLEWINDOWED = "Toggle Windowed Mode",

    --ElvUI
    ELVUIBAR1BUTTON1 = "ElvUI Bar 1 Button 1",
    ELVUIBAR1BUTTON2 = "ElvUI Bar 1 Button 2",
    ELVUIBAR1BUTTON3 = "ElvUI Bar 1 Button 3",
    ELVUIBAR1BUTTON4 = "ElvUI Bar 1 Button 4",
    ELVUIBAR1BUTTON5 = "ElvUI Bar 1 Button 5",
    ELVUIBAR1BUTTON6 = "ElvUI Bar 1 Button 6",
    ELVUIBAR1BUTTON7 = "ElvUI Bar 1 Button 7",
    ELVUIBAR1BUTTON8 = "ElvUI Bar 1 Button 8",
    ELVUIBAR1BUTTON9 = "ElvUI Bar 1 Button 9",
    ELVUIBAR1BUTTON10 = "ElvUI Bar 1 Button 10",
    ELVUIBAR1BUTTON11 = "ElvUI Bar 1 Button 11",
    ELVUIBAR1BUTTON12 = "ElvUI Bar 1 Button 12",
    ELVUIBAR2BUTTON1 = "ElvUI Bar 2 Button 1",
    ELVUIBAR2BUTTON2 = "ElvUI Bar 2 Button 2",
    ELVUIBAR2BUTTON3 = "ElvUI Bar 2 Button 3",
    ELVUIBAR2BUTTON4 = "ElvUI Bar 2 Button 4",
    ELVUIBAR2BUTTON5 = "ElvUI Bar 2 Button 5",
    ELVUIBAR2BUTTON6 = "ElvUI Bar 2 Button 6",
    ELVUIBAR2BUTTON7 = "ElvUI Bar 2 Button 7",
    ELVUIBAR2BUTTON8 = "ElvUI Bar 2 Button 8",
    ELVUIBAR2BUTTON9 = "ElvUI Bar 2 Button 9",
    ELVUIBAR2BUTTON10 = "ElvUI Bar 2 Button 10",
    ELVUIBAR2BUTTON11 = "ElvUI Bar 2 Button 11",
    ELVUIBAR2BUTTON12 = "ElvUI Bar 2 Button 12",
    ELVUIBAR3BUTTON1 = "ElvUI Bar 3 Button 1",
    ELVUIBAR3BUTTON2 = "ElvUI Bar 3 Button 2",
    ELVUIBAR3BUTTON3 = "ElvUI Bar 3 Button 3",
    ELVUIBAR3BUTTON4 = "ElvUI Bar 3 Button 4",
    ELVUIBAR3BUTTON5 = "ElvUI Bar 3 Button 5",
    ELVUIBAR3BUTTON6 = "ElvUI Bar 3 Button 6",
    ELVUIBAR3BUTTON7 = "ElvUI Bar 3 Button 7",
    ELVUIBAR3BUTTON8 = "ElvUI Bar 3 Button 8",
    ELVUIBAR3BUTTON9 = "ElvUI Bar 3 Button 9",
    ELVUIBAR3BUTTON10 = "ElvUI Bar 3 Button 10",
    ELVUIBAR3BUTTON11 = "ElvUI Bar 3 Button 11",
    ELVUIBAR3BUTTON12 = "ElvUI Bar 3 Button 12",
    ELVUIBAR4BUTTON1 = "ElvUI Bar 4 Button 1",
    ELVUIBAR4BUTTON2 = "ElvUI Bar 4 Button 2",
    ELVUIBAR4BUTTON3 = "ElvUI Bar 4 Button 3",
    ELVUIBAR4BUTTON4 = "ElvUI Bar 4 Button 4",
    ELVUIBAR4BUTTON5 = "ElvUI Bar 4 Button 5",
    ELVUIBAR4BUTTON6 = "ElvUI Bar 4 Button 6",
    ELVUIBAR4BUTTON7 = "ElvUI Bar 4 Button 7",
    ELVUIBAR4BUTTON8 = "ElvUI Bar 4 Button 8",
    ELVUIBAR4BUTTON9 = "ElvUI Bar 4 Button 9",
    ELVUIBAR4BUTTON10 = "ElvUI Bar 4 Button 10",
    ELVUIBAR4BUTTON11 = "ElvUI Bar 4 Button 11",
    ELVUIBAR4BUTTON12 = "ElvUI Bar 4 Button 12",
    ELVUIBAR5BUTTON1 = "ElvUI Bar 5 Button 1",
    ELVUIBAR5BUTTON2 = "ElvUI Bar 5 Button 2",
    ELVUIBAR5BUTTON3 = "ElvUI Bar 5 Button 3",
    ELVUIBAR5BUTTON4 = "ElvUI Bar 5 Button 4",
    ELVUIBAR5BUTTON5 = "ElvUI Bar 5 Button 5",
    ELVUIBAR5BUTTON6 = "ElvUI Bar 5 Button 6",
    ELVUIBAR5BUTTON7 = "ElvUI Bar 5 Button 7",
    ELVUIBAR5BUTTON8 = "ElvUI Bar 5 Button 8",
    ELVUIBAR5BUTTON9 = "ElvUI Bar 5 Button 9",
    ELVUIBAR5BUTTON10 = "ElvUI Bar 5 Button 10",
    ELVUIBAR5BUTTON11 = "ElvUI Bar 5 Button 11",
    ELVUIBAR5BUTTON12 = "ElvUI Bar 5 Button 12",
    ELVUIBAR6BUTTON1 = "ElvUI Bar 6 Button 1",
    ELVUIBAR6BUTTON2 = "ElvUI Bar 6 Button 2",
    ELVUIBAR6BUTTON3 = "ElvUI Bar 6 Button 3",
    ELVUIBAR6BUTTON4 = "ElvUI Bar 6 Button 4",
    ELVUIBAR6BUTTON5 = "ElvUI Bar 6 Button 5",
    ELVUIBAR6BUTTON6 = "ElvUI Bar 6 Button 6",
    ELVUIBAR6BUTTON7 = "ElvUI Bar 6 Button 7",
    ELVUIBAR6BUTTON8 = "ElvUI Bar 6 Button 8",
    ELVUIBAR6BUTTON9 = "ElvUI Bar 6 Button 9",
    ELVUIBAR6BUTTON10 = "ElvUI Bar 6 Button 10",
    ELVUIBAR6BUTTON11 = "ElvUI Bar 6 Button 11",
    ELVUIBAR6BUTTON12 = "ElvUI Bar 6 Button 12",
    ELVUIBAR7BUTTON1 = "ElvUI Bar 7 Button 1",
    ELVUIBAR7BUTTON2 = "ElvUI Bar 7 Button 2",
    ELVUIBAR7BUTTON3 = "ElvUI Bar 7 Button 3",
    ELVUIBAR7BUTTON4 = "ElvUI Bar 7 Button 4",
    ELVUIBAR7BUTTON5 = "ElvUI Bar 7 Button 5",
    ELVUIBAR7BUTTON6 = "ElvUI Bar 7 Button 6",
    ELVUIBAR7BUTTON7 = "ElvUI Bar 7 Button 7",
    ELVUIBAR7BUTTON8 = "ElvUI Bar 7 Button 8",
    ELVUIBAR7BUTTON9 = "ElvUI Bar 7 Button 9",
    ELVUIBAR7BUTTON10 = "ElvUI Bar 7 Button 10",
    ELVUIBAR7BUTTON11 = "ElvUI Bar 7 Button 11",
    ELVUIBAR7BUTTON12 = "ElvUI Bar 7 Button 12",
    ELVUIBAR8BUTTON1 = "ElvUI Bar 8 Button 1",
    ELVUIBAR8BUTTON2 = "ElvUI Bar 8 Button 2",
    ELVUIBAR8BUTTON3 = "ElvUI Bar 8 Button 3",
    ELVUIBAR8BUTTON4 = "ElvUI Bar 8 Button 4",
    ELVUIBAR8BUTTON5 = "ElvUI Bar 8 Button 5",
    ELVUIBAR8BUTTON6 = "ElvUI Bar 8 Button 6",
    ELVUIBAR8BUTTON7 = "ElvUI Bar 8 Button 7",
    ELVUIBAR8BUTTON8 = "ElvUI Bar 8 Button 8",
    ELVUIBAR8BUTTON9 = "ElvUI Bar 8 Button 9",
    ELVUIBAR8BUTTON10 = "ElvUI Bar 8 Button 10",
    ELVUIBAR8BUTTON11 = "ElvUI Bar 8 Button 11",
    ELVUIBAR8BUTTON12 = "ElvUI Bar 8 Button 12",
    ELVUIBAR9BUTTON1 = "ElvUI Bar 9 Button 1",
    ELVUIBAR9BUTTON2 = "ElvUI Bar 9 Button 2",
    ELVUIBAR9BUTTON3 = "ElvUI Bar 9 Button 3",
    ELVUIBAR9BUTTON4 = "ElvUI Bar 9 Button 4",
    ELVUIBAR9BUTTON5 = "ElvUI Bar 9 Button 5",
    ELVUIBAR9BUTTON6 = "ElvUI Bar 9 Button 6",
    ELVUIBAR9BUTTON7 = "ElvUI Bar 9 Button 7",
    ELVUIBAR9BUTTON8 = "ElvUI Bar 9 Button 8",
    ELVUIBAR9BUTTON9 = "ElvUI Bar 9 Button 9",
    ELVUIBAR9BUTTON10 = "ElvUI Bar 9 Button 10",
    ELVUIBAR9BUTTON11 = "ElvUI Bar 9 Button 11",
    ELVUIBAR9BUTTON12 = "ElvUI Bar 9 Button 12",
    ELVUIBAR10BUTTON1 = "ElvUI Bar 10 Button 1",
    ELVUIBAR10BUTTON2 = "ElvUI Bar 10 Button 2",
    ELVUIBAR10BUTTON3 = "ElvUI Bar 10 Button 3",
    ELVUIBAR10BUTTON4 = "ElvUI Bar 10 Button 4",
    ELVUIBAR10BUTTON5 = "ElvUI Bar 10 Button 5",
    ELVUIBAR10BUTTON6 = "ElvUI Bar 10 Button 6",
    ELVUIBAR10BUTTON7 = "ElvUI Bar 10 Button 7",
    ELVUIBAR10BUTTON8 = "ElvUI Bar 10 Button 8",
    ELVUIBAR10BUTTON9 = "ElvUI Bar 10 Button 9",
    ELVUIBAR10BUTTON10 = "ElvUI Bar 10 Button 10",
    ELVUIBAR10BUTTON11 = "ElvUI Bar 10 Button 11",
    ELVUIBAR10BUTTON12 = "ElvUI Bar 10 Button 12",
    ELVUIBAR11BUTTON1 = "ElvUI Bar 11 Button 1",
    ELVUIBAR11BUTTON2 = "ElvUI Bar 11 Button 2",
    ELVUIBAR11BUTTON3 = "ElvUI Bar 11 Button 3",
    ELVUIBAR11BUTTON4 = "ElvUI Bar 11 Button 4",
    ELVUIBAR11BUTTON5 = "ElvUI Bar 11 Button 5",
    ELVUIBAR11BUTTON6 = "ElvUI Bar 11 Button 6",
    ELVUIBAR11BUTTON7 = "ElvUI Bar 11 Button 7",
    ELVUIBAR11BUTTON8 = "ElvUI Bar 11 Button 8",
    ELVUIBAR11BUTTON9 = "ElvUI Bar 11 Button 9",
    ELVUIBAR11BUTTON10 = "ElvUI Bar 11 Button 10",
    ELVUIBAR11BUTTON11 = "ElvUI Bar 11 Button 11",
    ELVUIBAR11BUTTON12 = "ElvUI Bar 11 Button 12",
    ELVUIBAR12BUTTON1 = "ElvUI Bar 12 Button 1",
    ELVUIBAR12BUTTON2 = "ElvUI Bar 12 Button 2",
    ELVUIBAR12BUTTON3 = "ElvUI Bar 12 Button 3",
    ELVUIBAR12BUTTON4 = "ElvUI Bar 12 Button 4",
    ELVUIBAR12BUTTON5 = "ElvUI Bar 12 Button 5",
    ELVUIBAR12BUTTON6 = "ElvUI Bar 12 Button 6",
    ELVUIBAR12BUTTON7 = "ElvUI Bar 12 Button 7",
    ELVUIBAR12BUTTON8 = "ElvUI Bar 12 Button 8",
    ELVUIBAR12BUTTON9 = "ElvUI Bar 12 Button 9",
    ELVUIBAR12BUTTON10 = "ElvUI Bar 12 Button 10",
    ELVUIBAR12BUTTON11 = "ElvUI Bar 12 Button 11",
    ELVUIBAR12BUTTON12 = "ElvUI Bar 12 Button 12",
    ELVUIBAR13BUTTON1 = "ElvUI Bar 13 Button 1",
    ELVUIBAR13BUTTON2 = "ElvUI Bar 13 Button 2",
    ELVUIBAR13BUTTON3 = "ElvUI Bar 13 Button 3",
    ELVUIBAR13BUTTON4 = "ElvUI Bar 13 Button 4",
    ELVUIBAR13BUTTON5 = "ElvUI Bar 13 Button 5",
    ELVUIBAR13BUTTON6 = "ElvUI Bar 13 Button 6",
    ELVUIBAR13BUTTON7 = "ElvUI Bar 13 Button 7",
    ELVUIBAR13BUTTON8 = "ElvUI Bar 13 Button 8",
    ELVUIBAR13BUTTON9 = "ElvUI Bar 13 Button 9",
    ELVUIBAR13BUTTON10 = "ElvUI Bar 13 Button 10",
    ELVUIBAR13BUTTON11 = "ElvUI Bar 13 Button 11",
    ELVUIBAR13BUTTON12 = "ElvUI Bar 13 Button 12",
    ELVUIBAR14BUTTON1 = "ElvUI Bar 14 Button 1",
    ELVUIBAR14BUTTON2 = "ElvUI Bar 14 Button 2",
    ELVUIBAR14BUTTON3 = "ElvUI Bar 14 Button 3",
    ELVUIBAR14BUTTON4 = "ElvUI Bar 14 Button 4",
    ELVUIBAR14BUTTON5 = "ElvUI Bar 14 Button 5",
    ELVUIBAR14BUTTON6 = "ElvUI Bar 14 Button 6",
    ELVUIBAR14BUTTON7 = "ElvUI Bar 14 Button 7",
    ELVUIBAR14BUTTON8 = "ElvUI Bar 14 Button 8",
    ELVUIBAR14BUTTON9 = "ElvUI Bar 14 Button 9",
    ELVUIBAR14BUTTON10 = "ElvUI Bar 14 Button 10",
    ELVUIBAR14BUTTON11 = "ElvUI Bar 14 Button 11",
    ELVUIBAR14BUTTON12 = "ElvUI Bar 14 Button 12",
    ELVUIBAR15BUTTON1 = "ElvUI Bar 15 Button 1",
    ELVUIBAR15BUTTON2 = "ElvUI Bar 15 Button 2",
    ELVUIBAR15BUTTON3 = "ElvUI Bar 15 Button 3",
    ELVUIBAR15BUTTON4 = "ElvUI Bar 15 Button 4",
    ELVUIBAR15BUTTON5 = "ElvUI Bar 15 Button 5",
    ELVUIBAR15BUTTON6 = "ElvUI Bar 15 Button 6",
    ELVUIBAR15BUTTON7 = "ElvUI Bar 15 Button 7",
    ELVUIBAR15BUTTON8 = "ElvUI Bar 15 Button 8",
    ELVUIBAR15BUTTON9 = "ElvUI Bar 15 Button 9",
    ELVUIBAR15BUTTON10 = "ElvUI Bar 15 Button 10",
    ELVUIBAR15BUTTON11 = "ElvUI Bar 15 Button 11",
    ELVUIBAR15BUTTON12 = "ElvUI Bar 15 Button 12",
}

addon.action_mapping = {

    ["Movement Keys"] = {
        { "Move and Steer",         "MOVEANDSTEER" },
        { "Move Forward",           "MOVEFORWARD" },
        { "Move Backward",          "MOVEBACKWARD" },
        { "Turn Left",              "TURNLEFT" },
        { "Turn Right",             "TURNRIGHT" },
        { "Strafe Left",            "STRAFELEFT" },
        { "Strafe Right",           "STRAFERIGHT" },
        { "Jump",                   "JUMP" },
        { "Sit/Move Down",          "SITORSTAND" },
        { "Sheath/Unsheath Weapon", "TOGGLESHEATH" },
        { "Toggle Autorun",         "TOGGLEAUTORUN" },
        { "Start Autorun",          "STARTAUTORUN" },
        { "Stop Autorun",           "STOPAUTORUN" },
        { "Pitch Up",               "PITCHUP" },
        { "Pitch Down",             "PITCHDOWN" },
        { "Toggle Run/Walk",        "TOGGLERUN" },
        { "Follow Target",          "FOLLOWTARGET" },
    },

    ["Action Bar"] = {
        { "Action Button 1",          "ACTIONBUTTON1" },
        { "Action Button 2",          "ACTIONBUTTON2" },
        { "Action Button 3",          "ACTIONBUTTON3" },
        { "Action Button 4",          "ACTIONBUTTON4" },
        { "Action Button 5",          "ACTIONBUTTON5" },
        { "Action Button 6",          "ACTIONBUTTON6" },
        { "Action Button 7",          "ACTIONBUTTON7" },
        { "Action Button 8",          "ACTIONBUTTON8" },
        { "Action Button 9",          "ACTIONBUTTON9" },
        { "Action Button 10",         "ACTIONBUTTON10" },
        { "Action Button 11",         "ACTIONBUTTON11" },
        { "Action Button 12",         "ACTIONBUTTON12" },
        { "Extra Action Button 1",    "EXTRAACTIONBUTTON1" },
        { "Pet Action Button 1",      "BONUSACTIONBUTTON1" },
        { "Pet Action Button 2",      "BONUSACTIONBUTTON2" },
        { "Pet Action Button 3",      "BONUSACTIONBUTTON3" },
        { "Pet Action Button 4",      "BONUSACTIONBUTTON4" },
        { "Pet Action Button 5",      "BONUSACTIONBUTTON5" },
        { "Pet Action Button 6",      "BONUSACTIONBUTTON6" },
        { "Pet Action Button 7",      "BONUSACTIONBUTTON7" },
        { "Pet Action Button 8",      "BONUSACTIONBUTTON8" },
        { "Pet Action Button 9",      "BONUSACTIONBUTTON9" },
        { "Pet Action Button 10",     "BONUSACTIONBUTTON10" },
        { "Action Page 1",            "ACTIONPAGE1" },
        { "Action Page 2",            "ACTIONPAGE2" },
        { "Action Page 3",            "ACTIONPAGE3" },
        { "Action Page 4",            "ACTIONPAGE4" },
        { "Action Page 5",            "ACTIONPAGE5" },
        { "Action Page 6",            "ACTIONPAGE6" },
        { "Previous Action Bar",      "PREVIOUSACTIONPAGE" },
        { "Next Action Bar",          "NEXTACTIONPAGE" },
        { "Toggle Action Bar Lock",   "TOGGLEACTIONBARLOCK" },
        { "Toggle Self Cast",         "TOGGLEAUTOSELFCAST" },
        { "Special Action Button 1",  "SHAPESHIFTBUTTON1" },
        { "Special Action Button 2",  "SHAPESHIFTBUTTON2" },
        { "Special Action Button 3",  "SHAPESHIFTBUTTON3" },
        { "Special Action Button 4",  "SHAPESHIFTBUTTON4" },
        { "Special Action Button 5",  "SHAPESHIFTBUTTON5" },
        { "Special Action Button 6",  "SHAPESHIFTBUTTON6" },
        { "Special Action Button 7",  "SHAPESHIFTBUTTON7" },
        { "Special Action Button 8",  "SHAPESHIFTBUTTON8" },
        { "Special Action Button 9",  "SHAPESHIFTBUTTON9" },
        { "Special Action Button 10", "SHAPESHIFTBUTTON10" },
    },

    ["Action Bar 2"] = {
        { "Action Bar 2 Button 1",  "MULTIACTIONBAR1BUTTON1" },
        { "Action Bar 2 Button 2",  "MULTIACTIONBAR1BUTTON2" },
        { "Action Bar 2 Button 3",  "MULTIACTIONBAR1BUTTON3" },
        { "Action Bar 2 Button 4",  "MULTIACTIONBAR1BUTTON4" },
        { "Action Bar 2 Button 5",  "MULTIACTIONBAR1BUTTON5" },
        { "Action Bar 2 Button 6",  "MULTIACTIONBAR1BUTTON6" },
        { "Action Bar 2 Button 7",  "MULTIACTIONBAR1BUTTON7" },
        { "Action Bar 2 Button 8",  "MULTIACTIONBAR1BUTTON8" },
        { "Action Bar 2 Button 9",  "MULTIACTIONBAR1BUTTON9" },
        { "Action Bar 2 Button 10", "MULTIACTIONBAR1BUTTON10" },
        { "Action Bar 2 Button 11", "MULTIACTIONBAR1BUTTON11" },
        { "Action Bar 2 Button 12", "MULTIACTIONBAR1BUTTON12" },
    },

    ["Action Bar 3"] = {
        { "Action Bar 3 Button 1",  "MULTIACTIONBAR2BUTTON1" },
        { "Action Bar 3 Button 2",  "MULTIACTIONBAR2BUTTON2" },
        { "Action Bar 3 Button 3",  "MULTIACTIONBAR2BUTTON3" },
        { "Action Bar 3 Button 4",  "MULTIACTIONBAR2BUTTON4" },
        { "Action Bar 3 Button 5",  "MULTIACTIONBAR2BUTTON5" },
        { "Action Bar 3 Button 6",  "MULTIACTIONBAR2BUTTON6" },
        { "Action Bar 3 Button 7",  "MULTIACTIONBAR2BUTTON7" },
        { "Action Bar 3 Button 8",  "MULTIACTIONBAR2BUTTON8" },
        { "Action Bar 3 Button 9",  "MULTIACTIONBAR2BUTTON9" },
        { "Action Bar 3 Button 10", "MULTIACTIONBAR2BUTTON10" },
        { "Action Bar 3 Button 11", "MULTIACTIONBAR2BUTTON11" },
        { "Action Bar 3 Button 12", "MULTIACTIONBAR2BUTTON12" },
    },

    ["Action Bar 4"] = {
        { "Action Bar 4 Button 1",  "MULTIACTIONBAR3BUTTON1" },
        { "Action Bar 4 Button 2",  "MULTIACTIONBAR3BUTTON2" },
        { "Action Bar 4 Button 3",  "MULTIACTIONBAR3BUTTON3" },
        { "Action Bar 4 Button 4",  "MULTIACTIONBAR3BUTTON4" },
        { "Action Bar 4 Button 5",  "MULTIACTIONBAR3BUTTON5" },
        { "Action Bar 4 Button 6",  "MULTIACTIONBAR3BUTTON6" },
        { "Action Bar 4 Button 7",  "MULTIACTIONBAR3BUTTON7" },
        { "Action Bar 4 Button 8",  "MULTIACTIONBAR3BUTTON8" },
        { "Action Bar 4 Button 9",  "MULTIACTIONBAR3BUTTON9" },
        { "Action Bar 4 Button 10", "MULTIACTIONBAR3BUTTON10" },
        { "Action Bar 4 Button 11", "MULTIACTIONBAR3BUTTON11" },
        { "Action Bar 4 Button 12", "MULTIACTIONBAR3BUTTON12" },
    },

    ["Action Bar 5"] = {
        { "Action Bar 5 Button 1",  "MULTIACTIONBAR4BUTTON1" },
        { "Action Bar 5 Button 2",  "MULTIACTIONBAR4BUTTON2" },
        { "Action Bar 5 Button 3",  "MULTIACTIONBAR4BUTTON3" },
        { "Action Bar 5 Button 4",  "MULTIACTIONBAR4BUTTON4" },
        { "Action Bar 5 Button 5",  "MULTIACTIONBAR4BUTTON5" },
        { "Action Bar 5 Button 6",  "MULTIACTIONBAR4BUTTON6" },
        { "Action Bar 5 Button 7",  "MULTIACTIONBAR4BUTTON7" },
        { "Action Bar 5 Button 8",  "MULTIACTIONBAR4BUTTON8" },
        { "Action Bar 5 Button 9",  "MULTIACTIONBAR4BUTTON9" },
        { "Action Bar 5 Button 10", "MULTIACTIONBAR4BUTTON10" },
        { "Action Bar 5 Button 11", "MULTIACTIONBAR4BUTTON11" },
        { "Action Bar 5 Button 12", "MULTIACTIONBAR4BUTTON12" },
    },

    ["Action Bar 6"] = {
        { "Action Bar 6 Button 1",  "MULTIACTIONBAR5BUTTON1" },
        { "Action Bar 6 Button 2",  "MULTIACTIONBAR5BUTTON2" },
        { "Action Bar 6 Button 3",  "MULTIACTIONBAR5BUTTON3" },
        { "Action Bar 6 Button 4",  "MULTIACTIONBAR5BUTTON4" },
        { "Action Bar 6 Button 5",  "MULTIACTIONBAR5BUTTON5" },
        { "Action Bar 6 Button 6",  "MULTIACTIONBAR5BUTTON6" },
        { "Action Bar 6 Button 7",  "MULTIACTIONBAR5BUTTON7" },
        { "Action Bar 6 Button 8",  "MULTIACTIONBAR5BUTTON8" },
        { "Action Bar 6 Button 9",  "MULTIACTIONBAR5BUTTON9" },
        { "Action Bar 6 Button 10", "MULTIACTIONBAR5BUTTON10" },
        { "Action Bar 6 Button 11", "MULTIACTIONBAR5BUTTON11" },
        { "Action Bar 6 Button 12", "MULTIACTIONBAR5BUTTON12" },
    },

    ["Action Bar 7"] = {
        { "Action Bar 7 Button 1",  "MULTIACTIONBAR6BUTTON1" },
        { "Action Bar 7 Button 2",  "MULTIACTIONBAR6BUTTON2" },
        { "Action Bar 7 Button 3",  "MULTIACTIONBAR6BUTTON3" },
        { "Action Bar 7 Button 4",  "MULTIACTIONBAR6BUTTON4" },
        { "Action Bar 7 Button 5",  "MULTIACTIONBAR6BUTTON5" },
        { "Action Bar 7 Button 6",  "MULTIACTIONBAR6BUTTON6" },
        { "Action Bar 7 Button 7",  "MULTIACTIONBAR6BUTTON7" },
        { "Action Bar 7 Button 8",  "MULTIACTIONBAR6BUTTON8" },
        { "Action Bar 7 Button 9",  "MULTIACTIONBAR6BUTTON9" },
        { "Action Bar 7 Button 10", "MULTIACTIONBAR6BUTTON10" },
        { "Action Bar 7 Button 11", "MULTIACTIONBAR6BUTTON11" },
        { "Action Bar 7 Button 12", "MULTIACTIONBAR6BUTTON12" },
    },

    ["Action Bar 8"] = {
        { "Action Bar 8 Button 1",  "MULTIACTIONBAR7BUTTON1" },
        { "Action Bar 8 Button 2",  "MULTIACTIONBAR7BUTTON2" },
        { "Action Bar 8 Button 3",  "MULTIACTIONBAR7BUTTON3" },
        { "Action Bar 8 Button 4",  "MULTIACTIONBAR7BUTTON4" },
        { "Action Bar 8 Button 5",  "MULTIACTIONBAR7BUTTON5" },
        { "Action Bar 8 Button 6",  "MULTIACTIONBAR7BUTTON6" },
        { "Action Bar 8 Button 7",  "MULTIACTIONBAR7BUTTON7" },
        { "Action Bar 8 Button 8",  "MULTIACTIONBAR7BUTTON8" },
        { "Action Bar 8 Button 9",  "MULTIACTIONBAR7BUTTON9" },
        { "Action Bar 8 Button 10", "MULTIACTIONBAR7BUTTON10" },
        { "Action Bar 8 Button 11", "MULTIACTIONBAR7BUTTON11" },
        { "Action Bar 8 Button 12", "MULTIACTIONBAR7BUTTON12" },
    },

    ["Interface Panel"] = {
        { "Toggle Game Menu",             "TOGGLEGAMEMENU" },
        { "Toggle Backpack",              "TOGGLEBACKPACK" },
        { "Toggle Reagent Bag",           "TOGGLEREAGENTBAG1" },
        { "Toggle Bag 1",                 "TOGGLEBAG1" },
        { "Toggle Bag 2",                 "TOGGLEBAG2" },
        { "Toggle Bag 3",                 "TOGGLEBAG3" },
        { "Toggle Bag 4",                 "TOGGLEBAG4" },
        { "Open All Bags",                "OPENALLBAGS" },
        { "Toggle Character Pane",        "TOGGLECHARACTER0" },
        { "Toggle Reputation Pane",       "TOGGLECHARACTER2" },
        { "Toggle Currency Frame",        "TOGGLECURRENCY" },
        { "Toggle Spellbook",             "TOGGLESPELLBOOK" },
        { "Toggle Profession Book",       "TOGGLEPROFESSIONBOOK" },
        { "Toggle Pet Book",              "TOGGLEPETBOOK" },
        { "Toggle Talent Pane",           "TOGGLETALENTS" },
        { "Toggle Achievement Frame",     "TOGGLEACHIEVEMENT" },
        { "Toggle Statistics Frame",      "TOGGLESTATISTICS" },
        { "Toggle Quest Log",             "TOGGLEQUESTLOG" },
        { "Toggle World Map Pane",        "TOGGLEWORLDMAP" },
        { "Toggle World Map Size",        "TOGGLEWORLDMAPSIZE" },
        { "Toggle Minimap",               "TOGGLEMINIMAP" },
        { "Toggle Zone Map",              "TOGGLEBATTLEFIELDMINIMAP" },
        { "Toggle Score Screen",          "TOGGLEWORLDSTATESCORES" },
        { "Toggle Guild Pane",            "TOGGLEGUILDTAB" },
        { "Toggle Social Pane",           "TOGGLESOCIAL" },
        { "Toggle Friends Pane",          "TOGGLEFRIENDSTAB" },
        { "Toggle Quick Join",            "TOGGLEQUICKJOINTAB" },
        { "Toggle Who Pane",              "TOGGLEWHOTAB" },
        { "Toggle Chat Pane",             "TOGGLECHATTAB" },
        { "Toggle Raid Pane",             "TOGGLERAIDTAB" },
        { "Toggle Text To Speech Config", "TOGGLETEXTTOSPEECH" },
        { "Toggle Group Finder",          "TOGGLEGROUPFINDER" },
        { "Toggle Dungeons & Raids",      "TOGGLEDUNGEONSANDRAIDS" },
        { "Toggle PVP Pane",              "TOGGLECHARACTER4" },
        { "Toggle Collections",           "TOGGLECOLLECTIONS" },
        { "Toggle Mount Journal",         "TOGGLECOLLECTIONSMOUNTJOURNAL" },
        { "Toggle Pet Journal",           "TOGGLECOLLECTIONSPETJOURNAL" },
        { "Toggle Toy Box",               "TOGGLECOLLECTIONSTOYBOX" },
        { "Toggle Heirlooms Pane",        "TOGGLECOLLECTIONSHEIRLOOM" },
        { "Toggle Appearances",           "TOGGLECOLLECTIONSWARDROBE" },
        { "Toggle Adventure Guide",       "TOGGLEENCOUNTERJOURNAL" },
        { "Toggle Garrison Report",       "TOGGLEGARRISONLANDINGPAGE" },
    },

    ["Chat"] = {
        { "Open Chat",                      "OPENCHAT" },
        { "Open Chat Slash",                "OPENCHATSLASH" },
        { "Chat Page Up",                   "CHATPAGEUP" },
        { "Chat Page Down",                 "CHATPAGEDOWN" },
        { "Chat Bottom",                    "CHATBOTTOM" },
        { "Chat Reply",                     "REPLY" },
        { "Re-Whisper",                     "REPLY2" },
        { "Combat Log Page Up",             "COMBATLOGPAGEUP" },
        { "Combat Log Page Down",           "COMBATLOGPAGEDOWN" },
        { "Combat Log Bottom",              "COMBATLOGBOTTOM" },
        { "Toggle Combat Log",              "TOGGLECOMBATLOG" },
        { "Voice Chat: Toggle Mute Self",   "TOGGLE_VOICE_SELF_MUTE" },
        { "Voice Chat: Toggle Deafen Self", "TOGGLE_VOICE_SELF_DEAFEN" },
        { "Stop Text To Speech Playback",   "TEXT_TO_SPEECH_STOP" },
    },

    ["Targeting"] = {
        { "Target Nearest Enemy",            "TARGETNEARESTENEMY" },
        { "Target Previous Enemy",           "TARGETPREVIOUSENEMY" },
        { "Target Scan Enemy (Hold)",        "TARGETSCANENEMY" },
        { "Target Nearest Friend",           "TARGETNEARESTFRIEND" },
        { "Target Previous Friend",          "TARGETPREVIOUSFRIEND" },
        { "Target Nearest Enemy Player",     "TARGETNEARESTENEMYPLAYER" },
        { "Target Previous Enemy Player",    "TARGETPREVIOUSENEMYPLAYER" },
        { "Target Nearest Friendly Player",  "TARGETNEARESTFRIENDPLAYER" },
        { "Target Previous Friendly Player", "TARGETPREVIOUSFRIENDPLAYER" },
        { "Target Self",                     "TARGETSELF" },
        { "Target Party Member 1",           "TARGETPARTYMEMBER1" },
        { "Target Party Member 2",           "TARGETPARTYMEMBER2" },
        { "Target Party Member 3",           "TARGETPARTYMEMBER3" },
        { "Target Party Member 4",           "TARGETPARTYMEMBER4" },
        { "Target Pet",                      "TARGETPET" },
        { "Target Party Pet 1",              "TARGETPARTYPET1" },
        { "Target Party Pet 2",              "TARGETPARTYPET2" },
        { "Target Party Pet 3",              "TARGETPARTYPET3" },
        { "Target Party Pet 4",              "TARGETPARTYPET4" },
        { "Target Last Hostile",             "TARGETLASTHOSTILE" },
        { "Target Last Target",              "TARGETLASTTARGET" },
        { "Target Arena Enemy 1",            "TARGETARENA1" },
        { "Target Arena Enemy 2",            "TARGETARENA2" },
        { "Target Arena Enemy 3",            "TARGETARENA3" },
        { "Target Arena Enemy 4",            "TARGETARENA4" },
        { "Target Arena Enemy 5",            "TARGETARENA5" },
        { "Focus Arena Enemy 1",             "FOCUSARENA1" },
        { "Focus Arena Enemy 2",             "FOCUSARENA2" },
        { "Focus Arena Enemy 3",             "FOCUSARENA3" },
        { "Focus Arena Enemy 4",             "FOCUSARENA4" },
        { "Focus Arena Enemy 5",             "FOCUSARENA5" },
        { "Show Enemy Nameplates",           "NAMEPLATES" },
        { "Show Friendly Nameplates",        "FRIENDNAMEPLATES" },
        { "Show All Nameplates",             "ALLNAMEPLATES" },
        { "Interact With Mouseover",         "INTERACTMOUSEOVER" },
        { "Interact With Target",            "INTERACTTARGET" },
        { "Assist Target",                   "ASSISTTARGET" },
        { "Attack Target",                   "ATTACKTARGET" },
        { "Start Attack",                    "STARTATTACK" },
        { "Pet Attack",                      "PETATTACK" },
        { "Focus Target",                    "FOCUSTARGET" },
        { "Target Focus",                    "TARGETFOCUS" },
        { "Target Mouseover",                "TARGETMOUSEOVER" },
        { "Target Current Talker",           "TARGETTALKER" },
    },

    ["Target Markers"] = {
        { "Assign Star to Target",     "RAIDTARGET1" },
        { "Assign Circle to Target",   "RAIDTARGET2" },
        { "Assign Diamond to Target",  "RAIDTARGET3" },
        { "Assign Triangle to Target", "RAIDTARGET4" },
        { "Assign Moon to Target",     "RAIDTARGET5" },
        { "Assign Square to Target",   "RAIDTARGET6" },
        { "Assign Cross to Target",    "RAIDTARGET7" },
        { "Clear Target Marker Icon",  "RAIDTARGETNONE" },
    },

    ["Vehicle Controls"] = {
        { "Exit Vehicle",  "VEHICLEEXIT" },
        { "Previous Seat", "VEHICLEPREVSEAT" },
        { "Next Seat",     "VEHICLENEXTSEAT" },
        { "Aim Up",        "VEHICLEAIMUP" },
        { "Aim Down",      "VEHICLEAIMDOWN" },
        { "Aim Increment", "VEHICLEAIMINCREMENT" },
        { "Aim Decrement", "VEHICLEAIMDECREMENT" },
    },

    ["Camera"] = {
        { "Next View",     "NEXTVIEW" },
        { "Previous View", "PREVVIEW" },
        { "Zoom In",       "CAMERAZOOMIN" },
        { "Zoom Out",      "CAMERAZOOMOUT" },
        { "Set View 1",    "SETVIEW1" },
        { "Set View 2",    "SETVIEW2" },
        { "Set View 3",    "SETVIEW3" },
        { "Set View 4",    "SETVIEW4" },
        { "Set View 5",    "SETVIEW5" },
        { "Save View 1",   "SAVEVIEW1" },
        { "Save View 2",   "SAVEVIEW2" },
        { "Save View 3",   "SAVEVIEW3" },
        { "Save View 4",   "SAVEVIEW4" },
        { "Save View 5",   "SAVEVIEW5" },
        { "Reset View 1",  "RESETVIEW1" },
        { "Reset View 2",  "RESETVIEW2" },
        { "Reset View 3",  "RESETVIEW3" },
        { "Reset View 4",  "RESETVIEW4" },
        { "Reset View 5",  "RESETVIEW5" },
        { "Flip Camera",   "FLIPCAMERAYAW" },
        { "Center Camera", "CENTERCAMERA" },
    },

    ["Ping System"] = {
        { "Ping",      "TOGGLEPINGLISTENER" },
        { "Attack",    "PINGATTACK" },
        { "Warning",   "PINGWARNING" },
        { "On My Way", "PINGONMYWAY" },
        { "Assist",    "PINGASSIST" },
    },

    ["Miscellaneous"] = {
        { "Stop Casting",             "STOPCASTING" },
        { "Stop Attacking",           "STOPATTACK" },
        { "Dismount",                 "DISMOUNT" },
        { "Minimap Zoom In",          "MINIMAPZOOMIN" },
        { "Minimap Zoom Out",         "MINIMAPZOOMOUT" },
        { "Toggle Music",             "TOGGLEMUSIC" },
        { "Toggle Sound",             "TOGGLESOUND" },
        { "Master Volume Up",         "MASTERVOLUMEUP" },
        { "Master Volume Down",       "MASTERVOLUMEDOWN" },
        { "Toggle User Interface",    "TOGGLEUI" },
        { "Toggle Framerate Display", "TOGGLEFPS" },
        { "Screen Shot",              "SCREENSHOT" },
        { "Item Comparison Cycling",  "ITEMCOMPARISONCYCLING" },
        { "Toggle Graphics Settings", "TOGGLEGRAPHICSSETTINGS" },
        { "Toggle Self Highlight",    "TOGGLESELFHIGHLIGHT" },
        { "Toggle Windowed Mode",     "TOGGLEWINDOWED" },
    },
}

addon.shortcut_labels = {
    ["CAPSLOCK"] = "CAPS",
    ["PRINTSCREEN"] = "PRINT",
    ["SCROLLLOCK"] = "SCROLL",
    ["INSERT"] = "INS",
    ["PAGEUP"] = "PG UP",
    ["DELETE"] = "DEL",
    ["PAGEDOWN"] = "PG DN",
    ["NUMPAD0"] = "NUM0",
    ["NUMPAD1"] = "NUM1",
    ["NUMPAD2"] = "NUM2",
    ["NUMPAD3"] = "NUM3",
    ["NUMPAD4"] = "NUM4",
    ["NUMPAD5"] = "NUM5",
    ["NUMPAD6"] = "NUM6",
    ["NUMPAD7"] = "NUM7",
    ["NUMPAD8"] = "NUM8",
    ["NUMPAD9"] = "NUM9",
    ["NUMLOCK"] = "NUMLK",
    ["NUMPADDIV"] = "/",
    ["NUMPADMULT"] = "*",
    ["NUMPADSUB"] = "-",
    ["NUMPADADD"] = "+",
    ["NUMPADENTER"] = "ENTER",
    ["NUMPADDOT"] = "."
}

addon.action_slot_mapping = {
    --Action Bar 1
    ACTIONBUTTON1 = "1",
    ACTIONBUTTON2 = "2",
    ACTIONBUTTON3 = "3",
    ACTIONBUTTON4 = "4",
    ACTIONBUTTON5 = "5",
    ACTIONBUTTON6 = "6",
    ACTIONBUTTON7 = "7",
    ACTIONBUTTON8 = "8",
    ACTIONBUTTON9 = "9",
    ACTIONBUTTON10 = "10",
    ACTIONBUTTON11 = "11",
    ACTIONBUTTON12 = "12",

    --Action Bar 2
    MULTIACTIONBAR1BUTTON1 = "61",
    MULTIACTIONBAR1BUTTON2 = "62",
    MULTIACTIONBAR1BUTTON3 = "63",
    MULTIACTIONBAR1BUTTON4 = "64",
    MULTIACTIONBAR1BUTTON5 = "65",
    MULTIACTIONBAR1BUTTON6 = "66",
    MULTIACTIONBAR1BUTTON7 = "67",
    MULTIACTIONBAR1BUTTON8 = "68",
    MULTIACTIONBAR1BUTTON9 = "69",
    MULTIACTIONBAR1BUTTON10 = "70",
    MULTIACTIONBAR1BUTTON11 = "71",
    MULTIACTIONBAR1BUTTON12 = "72",

    --Action Bar 3
    MULTIACTIONBAR2BUTTON1 = "49",
    MULTIACTIONBAR2BUTTON2 = "50",
    MULTIACTIONBAR2BUTTON3 = "51",
    MULTIACTIONBAR2BUTTON4 = "52",
    MULTIACTIONBAR2BUTTON5 = "53",
    MULTIACTIONBAR2BUTTON6 = "54",
    MULTIACTIONBAR2BUTTON7 = "55",
    MULTIACTIONBAR2BUTTON8 = "56",
    MULTIACTIONBAR2BUTTON9 = "57",
    MULTIACTIONBAR2BUTTON10 = "58",
    MULTIACTIONBAR2BUTTON11 = "59",
    MULTIACTIONBAR2BUTTON12 = "60",

    --Action Bar 4
    MULTIACTIONBAR3BUTTON1 = "25",
    MULTIACTIONBAR3BUTTON2 = "26",
    MULTIACTIONBAR3BUTTON3 = "27",
    MULTIACTIONBAR3BUTTON4 = "28",
    MULTIACTIONBAR3BUTTON5 = "29",
    MULTIACTIONBAR3BUTTON6 = "30",
    MULTIACTIONBAR3BUTTON7 = "31",
    MULTIACTIONBAR3BUTTON8 = "32",
    MULTIACTIONBAR3BUTTON9 = "33",
    MULTIACTIONBAR3BUTTON10 = "34",
    MULTIACTIONBAR3BUTTON11 = "35",
    MULTIACTIONBAR3BUTTON12 = "36",

    --Action Bar 5
    MULTIACTIONBAR4BUTTON1 = "37",
    MULTIACTIONBAR4BUTTON2 = "38",
    MULTIACTIONBAR4BUTTON3 = "39",
    MULTIACTIONBAR4BUTTON4 = "40",
    MULTIACTIONBAR4BUTTON5 = "41",
    MULTIACTIONBAR4BUTTON6 = "42",
    MULTIACTIONBAR4BUTTON7 = "43",
    MULTIACTIONBAR4BUTTON8 = "44",
    MULTIACTIONBAR4BUTTON9 = "45",
    MULTIACTIONBAR4BUTTON10 = "46",
    MULTIACTIONBAR4BUTTON11 = "47",
    MULTIACTIONBAR4BUTTON12 = "48",

    --Action Bar 6
    MULTIACTIONBAR5BUTTON1 = "145",
    MULTIACTIONBAR5BUTTON2 = "146",
    MULTIACTIONBAR5BUTTON3 = "147",
    MULTIACTIONBAR5BUTTON4 = "148",
    MULTIACTIONBAR5BUTTON5 = "149",
    MULTIACTIONBAR5BUTTON6 = "150",
    MULTIACTIONBAR5BUTTON7 = "151",
    MULTIACTIONBAR5BUTTON8 = "152",
    MULTIACTIONBAR5BUTTON9 = "153",
    MULTIACTIONBAR5BUTTON10 = "154",
    MULTIACTIONBAR5BUTTON11 = "155",
    MULTIACTIONBAR5BUTTON12 = "156",

    --Action Bar 7
    MULTIACTIONBAR6BUTTON1 = "157",
    MULTIACTIONBAR6BUTTON2 = "158",
    MULTIACTIONBAR6BUTTON3 = "159",
    MULTIACTIONBAR6BUTTON4 = "160",
    MULTIACTIONBAR6BUTTON5 = "161",
    MULTIACTIONBAR6BUTTON6 = "162",
    MULTIACTIONBAR6BUTTON7 = "163",
    MULTIACTIONBAR6BUTTON8 = "164",
    MULTIACTIONBAR6BUTTON9 = "165",
    MULTIACTIONBAR6BUTTON10 = "166",
    MULTIACTIONBAR6BUTTON11 = "167",
    MULTIACTIONBAR6BUTTON12 = "168",

    --Action Bar 8
    MULTIACTIONBAR7BUTTON1 = "169",
    MULTIACTIONBAR7BUTTON2 = "170",
    MULTIACTIONBAR7BUTTON3 = "171",
    MULTIACTIONBAR7BUTTON4 = "172",
    MULTIACTIONBAR7BUTTON5 = "173",
    MULTIACTIONBAR7BUTTON6 = "174",
    MULTIACTIONBAR7BUTTON7 = "175",
    MULTIACTIONBAR7BUTTON8 = "176",
    MULTIACTIONBAR7BUTTON9 = "177",
    MULTIACTIONBAR7BUTTON10 = "178",
    MULTIACTIONBAR7BUTTON11 = "179",
    MULTIACTIONBAR7BUTTON12 = "180",
}

addon.button_texture_mapping = {
    -- Action Bar 1 Page 1
    ["1"] = ActionButton1,
    ["2"] = ActionButton2,
    ["3"] = ActionButton3,
    ["4"] = ActionButton4,
    ["5"] = ActionButton5,
    ["6"] = ActionButton6,
    ["7"] = ActionButton7,
    ["8"] = ActionButton8,
    ["9"] = ActionButton9,
    ["10"] = ActionButton10,
    ["11"] = ActionButton11,
    ["12"] = ActionButton12,

    -- Action Bar 1 Page 2
    ["13"] = ActionButton1,
    ["14"] = ActionButton2,
    ["15"] = ActionButton3,
    ["16"] = ActionButton4,
    ["17"] = ActionButton5,
    ["18"] = ActionButton6,
    ["19"] = ActionButton7,
    ["20"] = ActionButton8,
    ["21"] = ActionButton9,
    ["22"] = ActionButton10,
    ["23"] = ActionButton11,
    ["24"] = ActionButton12,

    -- Bonus Bar 1
    ["73"] = ActionButton1,
    ["74"] = ActionButton2,
    ["75"] = ActionButton3,
    ["76"] = ActionButton4,
    ["77"] = ActionButton5,
    ["78"] = ActionButton6,
    ["79"] = ActionButton7,
    ["80"] = ActionButton8,
    ["81"] = ActionButton9,
    ["82"] = ActionButton10,
    ["83"] = ActionButton11,
    ["84"] = ActionButton12,

    -- Bonus Bar 3
    ["97"] = ActionButton1,
    ["98"] = ActionButton2,
    ["99"] = ActionButton3,
    ["100"] = ActionButton4,
    ["101"] = ActionButton5,
    ["102"] = ActionButton6,
    ["103"] = ActionButton7,
    ["104"] = ActionButton8,
    ["105"] = ActionButton9,
    ["106"] = ActionButton10,
    ["107"] = ActionButton11,
    ["108"] = ActionButton12,

    -- Bonus Bar 4
    ["109"] = ActionButton1,
    ["110"] = ActionButton2,
    ["111"] = ActionButton3,
    ["112"] = ActionButton4,
    ["113"] = ActionButton5,
    ["114"] = ActionButton6,
    ["115"] = ActionButton7,
    ["116"] = ActionButton8,
    ["117"] = ActionButton9,
    ["118"] = ActionButton10,
    ["119"] = ActionButton11,
    ["120"] = ActionButton12,

    -- Action Bar 2
    ["61"] = MultiBarBottomLeftButton1,
    ["62"] = MultiBarBottomLeftButton2,
    ["63"] = MultiBarBottomLeftButton3,
    ["64"] = MultiBarBottomLeftButton4,
    ["65"] = MultiBarBottomLeftButton5,
    ["66"] = MultiBarBottomLeftButton6,
    ["67"] = MultiBarBottomLeftButton7,
    ["68"] = MultiBarBottomLeftButton8,
    ["69"] = MultiBarBottomLeftButton9,
    ["70"] = MultiBarBottomLeftButton10,
    ["71"] = MultiBarBottomLeftButton11,
    ["72"] = MultiBarBottomLeftButton12,

    -- Action Bar 3
    ["49"] = MultiBarBottomRightButton1,
    ["50"] = MultiBarBottomRightButton2,
    ["51"] = MultiBarBottomRightButton3,
    ["52"] = MultiBarBottomRightButton4,
    ["53"] = MultiBarBottomRightButton5,
    ["54"] = MultiBarBottomRightButton6,
    ["55"] = MultiBarBottomRightButton7,
    ["56"] = MultiBarBottomRightButton8,
    ["57"] = MultiBarBottomRightButton9,
    ["58"] = MultiBarBottomRightButton10,
    ["59"] = MultiBarBottomRightButton11,
    ["60"] = MultiBarBottomRightButton12,

    -- Action Bar 4
    ["25"] = MultiBarRightButton1,
    ["26"] = MultiBarRightButton2,
    ["27"] = MultiBarRightButton3,
    ["28"] = MultiBarRightButton4,
    ["29"] = MultiBarRightButton5,
    ["30"] = MultiBarRightButton6,
    ["31"] = MultiBarRightButton7,
    ["32"] = MultiBarRightButton8,
    ["33"] = MultiBarRightButton9,
    ["34"] = MultiBarRightButton10,
    ["35"] = MultiBarRightButton11,
    ["36"] = MultiBarRightButton12,

    -- Action Bar 5
    ["37"] = MultiBarLeftButton1,
    ["38"] = MultiBarLeftButton2,
    ["39"] = MultiBarLeftButton3,
    ["40"] = MultiBarLeftButton4,
    ["41"] = MultiBarLeftButton5,
    ["42"] = MultiBarLeftButton6,
    ["43"] = MultiBarLeftButton7,
    ["44"] = MultiBarLeftButton8,
    ["45"] = MultiBarLeftButton9,
    ["46"] = MultiBarLeftButton10,
    ["47"] = MultiBarLeftButton11,
    ["48"] = MultiBarLeftButton12,

    -- Action Bar 6
    ["145"] = MultiBar5Button1,
    ["146"] = MultiBar5Button2,
    ["147"] = MultiBar5Button3,
    ["148"] = MultiBar5Button4,
    ["149"] = MultiBar5Button5,
    ["150"] = MultiBar5Button6,
    ["151"] = MultiBar5Button7,
    ["152"] = MultiBar5Button8,
    ["153"] = MultiBar5Button9,
    ["154"] = MultiBar5Button10,
    ["155"] = MultiBar5Button11,
    ["156"] = MultiBar5Button12,

    -- Action Bar 7
    ["157"] = MultiBar6Button1,
    ["158"] = MultiBar6Button2,
    ["159"] = MultiBar6Button3,
    ["160"] = MultiBar6Button4,
    ["161"] = MultiBar6Button5,
    ["162"] = MultiBar6Button6,
    ["163"] = MultiBar6Button7,
    ["164"] = MultiBar6Button8,
    ["165"] = MultiBar6Button9,
    ["166"] = MultiBar6Button10,
    ["167"] = MultiBar6Button11,
    ["168"] = MultiBar6Button12,

    -- Action Bar 8
    ["169"] = MultiBar7Button1,
    ["170"] = MultiBar7Button2,
    ["171"] = MultiBar7Button3,
    ["172"] = MultiBar7Button4,
    ["173"] = MultiBar7Button5,
    ["174"] = MultiBar7Button6,
    ["175"] = MultiBar7Button7,
    ["176"] = MultiBar7Button8,
    ["177"] = MultiBar7Button9,
    ["178"] = MultiBar7Button10,
    ["179"] = MultiBar7Button11,
    ["180"] = MultiBar7Button12,

    -- Dragonriding
    ["121"] = ActionButton1,
    ["122"] = ActionButton2,
    ["123"] = ActionButton3,
    ["124"] = ActionButton4,
    ["125"] = ActionButton5,
    ["126"] = ActionButton6,
    ["127"] = ActionButton7,
    ["128"] = ActionButton8,
    ["129"] = ActionButton9,
    ["130"] = ActionButton10,
    ["131"] = ActionButton11,
    ["132"] = ActionButton12,
}
