KeyMappings = {
-- Movement Keys
    MOVEANDSTEER = "Move and Steer",
    MOVEFORWARD = "Move Forward",
    MOVEBACKWARD = "Move Backward",
    TURNLEFT = "Turn Left",
    TURNRIGHT = "Turn Right",
    STRAFELEFT = "Strafe Left",
    STRAFERIGHT = "Strafe Right",
    JUMP = "Jump",
    SITORSTAND = "Sit/Move Down",
    TOGGLESHEATH = "Sheath/Unsheath Weapon",
    TOGGLEAUTORUN = "Toggle Autorun",
    STARTAUTORUN = "Start Autorun",
    STOPAUTORUN = "Stop Autorun",
    PITCHUP = "Pitch Up",
    PITCHDOWN = "Pitch Down",
    TOGGLERUN = "Toggle Run/Walk",
    FOLLOWTARGET = "Follow Target",

--Action Bar
    ACTIONBUTTON1 = "Action Button 1",
    ACTIONBUTTON2 = "Action Button 2",
    ACTIONBUTTON3 = "Action Button 3",
    ACTIONBUTTON4 = "Action Button 4",
    ACTIONBUTTON5 = "Action Button 5",
    ACTIONBUTTON6 = "Action Button 6",
    ACTIONBUTTON7 = "Action Button 7",
    ACTIONBUTTON8 = "Action Button 8",
    ACTIONBUTTON9 = "Action Button 9",
    ACTIONBUTTON10 = "Action Button 10",
    ACTIONBUTTON11 = "Action Button 11",
    ACTIONBUTTON12 = "Action Button 12",

    EXTRAACTIONBUTTON1 = "Extra Action Button 1",

    BONUSACTIONBUTTON1 = "Pet Action Button 1",
    BONUSACTIONBUTTON2 = "Pet Action Button 2",
    BONUSACTIONBUTTON3 = "Pet Action Button 3",
    BONUSACTIONBUTTON4 = "Pet Action Button 4",
    BONUSACTIONBUTTON5 = "Pet Action Button 5",
    BONUSACTIONBUTTON6 = "Pet Action Button 6",
    BONUSACTIONBUTTON7 = "Pet Action Button 7",
    BONUSACTIONBUTTON8 = "Pet Action Button 8",
    BONUSACTIONBUTTON9 = "Pet Action Button 9",
    BONUSACTIONBUTTON10 = "Pet Action Button 10",

    ACTIONPAGE1 = "Action Page 1",
    ACTIONPAGE2 = "Action Page 2",
    ACTIONPAGE3 = "Action Page 3",
    ACTIONPAGE4 = "Action Page 4",
    ACTIONPAGE5 = "Action Page 5",
    ACTIONPAGE6 = "Action Page 6",

    PREVIOUSACTIONPAGE = "Previous Action Bar",
    NEXTACTIONPAGE = "Next Action Bar",
    TOGGLEACTIONBARLOCK = "Toggle Action Bar Lock",
    TOGGLEAUTOSELFCAST = "Toggle Self Cast",

    SHAPESHIFTBUTTON1 = "Special Action Button 1",
    SHAPESHIFTBUTTON2 = "Special Action Button 2",
    SHAPESHIFTBUTTON3 = "Special Action Button 3",
    SHAPESHIFTBUTTON4 = "Special Action Button 4",
    SHAPESHIFTBUTTON5 = "Special Action Button 5",
    SHAPESHIFTBUTTON6 = "Special Action Button 6",
    SHAPESHIFTBUTTON7 = "Special Action Button 7",
    SHAPESHIFTBUTTON8 = "Special Action Button 8",
    SHAPESHIFTBUTTON9 = "Special Action Button 9",
    SHAPESHIFTBUTTON10 = "Special Action Button 10",

--Action Bar 2
    MULTIACTIONBAR1BUTTON1 = "Action Bar 2 Button 1",
    MULTIACTIONBAR1BUTTON2 = "Action Bar 2 Button 2",
    MULTIACTIONBAR1BUTTON3 = "Action Bar 2 Button 3",
    MULTIACTIONBAR1BUTTON4 = "Action Bar 2 Button 4",
    MULTIACTIONBAR1BUTTON5 = "Action Bar 2 Button 5",
    MULTIACTIONBAR1BUTTON6 = "Action Bar 2 Button 6",
    MULTIACTIONBAR1BUTTON7 = "Action Bar 2 Button 7",
    MULTIACTIONBAR1BUTTON8 = "Action Bar 2 Button 8",
    MULTIACTIONBAR1BUTTON9 = "Action Bar 2 Button 9",
    MULTIACTIONBAR1BUTTON10 = "Action Bar 2 Button 10",
    MULTIACTIONBAR1BUTTON11 = "Action Bar 2 Button 11",
    MULTIACTIONBAR1BUTTON12 = "Action Bar 2 Button 12",

--Action Bar 3
    MULTIACTIONBAR2BUTTON1 = "Action Bar 3 Button 1",
    MULTIACTIONBAR2BUTTON2 = "Action Bar 3 Button 2",
    MULTIACTIONBAR2BUTTON3 = "Action Bar 3 Button 3",
    MULTIACTIONBAR2BUTTON4 = "Action Bar 3 Button 4",
    MULTIACTIONBAR2BUTTON5 = "Action Bar 3 Button 5",
    MULTIACTIONBAR2BUTTON6 = "Action Bar 3 Button 6",
    MULTIACTIONBAR2BUTTON7 = "Action Bar 3 Button 7",
    MULTIACTIONBAR2BUTTON8 = "Action Bar 3 Button 8",
    MULTIACTIONBAR2BUTTON9 = "Action Bar 3 Button 9",
    MULTIACTIONBAR2BUTTON10 = "Action Bar 3 Button 10",
    MULTIACTIONBAR2BUTTON11 = "Action Bar 3 Button 11",
    MULTIACTIONBAR2BUTTON12 = "Action Bar 3 Button 12",

--Action Bar 4
    MULTIACTIONBAR3BUTTON1 = "Action Bar 4 Button 1",
    MULTIACTIONBAR3BUTTON2 = "Action Bar 4 Button 2",
    MULTIACTIONBAR3BUTTON3 = "Action Bar 4 Button 3",
    MULTIACTIONBAR3BUTTON4 = "Action Bar 4 Button 4",
    MULTIACTIONBAR3BUTTON5 = "Action Bar 4 Button 5",
    MULTIACTIONBAR3BUTTON6 = "Action Bar 4 Button 6",
    MULTIACTIONBAR3BUTTON7 = "Action Bar 4 Button 7",
    MULTIACTIONBAR3BUTTON8 = "Action Bar 4 Button 8",
    MULTIACTIONBAR3BUTTON9 = "Action Bar 4 Button 9",
    MULTIACTIONBAR3BUTTON10 = "Action Bar 4 Button 10",
    MULTIACTIONBAR3BUTTON11 = "Action Bar 4 Button 11",
    MULTIACTIONBAR3BUTTON12 = "Action Bar 4 Button 12",

--Action Bar 5
    MULTIACTIONBAR4BUTTON1 = "Action Bar 5 Button 1",
    MULTIACTIONBAR4BUTTON2 = "Action Bar 5 Button 2",
    MULTIACTIONBAR4BUTTON3 = "Action Bar 5 Button 3",
    MULTIACTIONBAR4BUTTON4 = "Action Bar 5 Button 4",
    MULTIACTIONBAR4BUTTON5 = "Action Bar 5 Button 5",
    MULTIACTIONBAR4BUTTON6 = "Action Bar 5 Button 6",
    MULTIACTIONBAR4BUTTON7 = "Action Bar 5 Button 7",
    MULTIACTIONBAR4BUTTON8 = "Action Bar 5 Button 8",
    MULTIACTIONBAR4BUTTON9 = "Action Bar 5 Button 9",
    MULTIACTIONBAR4BUTTON10 = "Action Bar 5 Button 10",
    MULTIACTIONBAR4BUTTON11 = "Action Bar 5 Button 11",
    MULTIACTIONBAR4BUTTON12 = "Action Bar 5 Button 12",

--Action Bar 6
    MULTIACTIONBAR5BUTTON1 = "Action Bar 6 Button 1",
    MULTIACTIONBAR5BUTTON2 = "Action Bar 6 Button 2",
    MULTIACTIONBAR5BUTTON3 = "Action Bar 6 Button 3",
    MULTIACTIONBAR5BUTTON4 = "Action Bar 6 Button 4",
    MULTIACTIONBAR5BUTTON5 = "Action Bar 6 Button 5",
    MULTIACTIONBAR5BUTTON6 = "Action Bar 6 Button 6",
    MULTIACTIONBAR5BUTTON7 = "Action Bar 6 Button 7",
    MULTIACTIONBAR5BUTTON8 = "Action Bar 6 Button 8",
    MULTIACTIONBAR5BUTTON9 = "Action Bar 6 Button 9",
    MULTIACTIONBAR5BUTTON10 = "Action Bar 6 Button 10",
    MULTIACTIONBAR5BUTTON11 = "Action Bar 6 Button 11",
    MULTIACTIONBAR5BUTTON12 = "Action Bar 6 Button 12",

--Action Bar 7
    MULTIACTIONBAR6BUTTON1 = "Action Bar 7 Button 1",
    MULTIACTIONBAR6BUTTON2 = "Action Bar 7 Button 2",
    MULTIACTIONBAR6BUTTON3 = "Action Bar 7 Button 3",
    MULTIACTIONBAR6BUTTON4 = "Action Bar 7 Button 4",
    MULTIACTIONBAR6BUTTON5 = "Action Bar 7 Button 5",
    MULTIACTIONBAR6BUTTON6 = "Action Bar 7 Button 6",
    MULTIACTIONBAR6BUTTON7 = "Action Bar 7 Button 7",
    MULTIACTIONBAR6BUTTON8 = "Action Bar 7 Button 8",
    MULTIACTIONBAR6BUTTON9 = "Action Bar 7 Button 9",
    MULTIACTIONBAR6BUTTON10 = "Action Bar 7 Button 10",
    MULTIACTIONBAR6BUTTON11 = "Action Bar 7 Button 11",
    MULTIACTIONBAR6BUTTON12 = "Action Bar 7 Button 12",

--Action Bar 8
    MULTIACTIONBAR7BUTTON1 = "Action Bar 8 Button 1",
    MULTIACTIONBAR7BUTTON2 = "Action Bar 8 Button 2",
    MULTIACTIONBAR7BUTTON3 = "Action Bar 8 Button 3",
    MULTIACTIONBAR7BUTTON4 = "Action Bar 8 Button 4",
    MULTIACTIONBAR7BUTTON5 = "Action Bar 8 Button 5",
    MULTIACTIONBAR7BUTTON6 = "Action Bar 8 Button 6",
    MULTIACTIONBAR7BUTTON7 = "Action Bar 8 Button 7",
    MULTIACTIONBAR7BUTTON8 = "Action Bar 8 Button 8",
    MULTIACTIONBAR7BUTTON9 = "Action Bar 8 Button 9",
    MULTIACTIONBAR7BUTTON10 = "Action Bar 8 Button 10",
    MULTIACTIONBAR7BUTTON11 = "Action Bar 8 Button 11",
    MULTIACTIONBAR7BUTTON12 = "Action Bar 8 Button 12",

--Interface Panel
    TOGGLEGAMEMENU = "Toggle Game Menu",
    TOGGLEBACKPACK = "Toggle Backpack",
    TOGGLEREAGENTBAG1 = "Toggle Reagent Bag",
    TOGGLEBAG1 = "Toggle Bag 1",
    TOGGLEBAG2 = "Toggle Bag 2",
    TOGGLEBAG3 = "Toggle Bag 3",
    TOGGLEBAG4 = "Toggle Bag 4",
    OPENALLBAGS = "Open All Bags",

    TOGGLECHARACTER0 = "Toggle Character Pane",
    TOGGLECHARACTER2 = "Toggle Reputation Pane",
    TOGGLECURRENCY = "Toggle Currency Frame",

    TOGGLESPELLBOOK = "Toggle Spellbook",
    TOGGLEPROFESSIONBOOK = "Toggle Profession Book",
    TOGGLEPETBOOK = "Toggle Pet Book",
    TOGGLETALENTS = "Toggle Talent Pane",

    TOGGLEACHIEVEMENT = "Toggle Achievement Frame",
    TOGGLESTATISTICS = "Toggle Statistics Frame",

    TOGGLEQUESTLOG = "Toggle Quest Log",
    TOGGLEWORLDMAP = "Toggle World Map Pane",
    TOGGLEWORLDMAPSIZE = "Toggle World Map Size",
    TOGGLEMINIMAP = "Toggle Minimap",
    TOGGLEBATTLEFIELDMINIMAP = "Toggle Zone Map",
    TOGGLEWORLDSTATESCORES = "Toggle Score Screen",

    TOGGLEGUILDTAB = "Toggle Guild Pane",
    TOGGLESOCIAL = "Toggle Social Pane",
    TOGGLEFRIENDSTAB = "Toggle Friends Pane",
    TOGGLEQUICKJOINTAB = "Toggle Quick Join",
    TOGGLEWHOTAB = "Toggle Who Pane",
    TOGGLECHATTAB = "Toggle Chat Pane",
    TOGGLERAIDTAB = "Toggle Raid Pane",
    TOGGLETEXTTOSPEECH = "Toggle Text To Speech Config",

    TOGGLEGROUPFINDER = "Toggle Group Finder",
    TOGGLEDUNGEONSANDRAIDS = "Toggle Dungeons & Raids",
    TOGGLECHARACTER4 = "Toggle PVP Pane",

    TOGGLECOLLECTIONS = "Toggle Collections",
    TOGGLECOLLECTIONSMOUNTJOURNAL = "Toggle Mount Journal",
    TOGGLECOLLECTIONSPETJOURNAL = "Toggle Pet Journal",
    TOGGLECOLLECTIONSTOYBOX = "Toggle Toy Box",
    TOGGLECOLLECTIONSHEIRLOOM = "Toggle Heirlooms Pane",
    TOGGLECOLLECTIONSWARDROBE = "Toggle Appearances",

    TOGGLEENCOUNTERJOURNAL = "Toggle Adventure Guide",
    TOGGLEGARRISONLANDINGPAGE = "Toggle Garrison Report",

--Chat
    OPENCHAT = "Open Chat",
    OPENCHATSLASH = "Open Chat Slash",
    CHATPAGEUP = "Chat Page Up",
    CHATPAGEDOWN = "Chat Page Down",
    CHATBOTTOM = "Chat Bottom",
    REPLY = "Chat Reply",
    REPLY2 = "Re-Whisper",
    COMBATLOGPAGEUP = "Combat Log Page Up",
    COMBATLOGPAGEDOWN = "Combat Log Page Down",
    COMBATLOGBOTTOM = "Combat Log Bottom",
    TOGGLECOMBATLOG = "Toggle Combat Log",
    TOGGLE_VOICE_SELF_MUTE = "Voice Chat: Toggle Mute Self",
    TOGGLE_VOICE_SELF_DEAFEN = "Voice Chat: Toggle Deafen Self",
    --MISSING-- = "Voice Chat: Push to Talk"
    TEXT_TO_SPEECH_STOP = "Stop Text To Speech Playback",

--Targeting
    TARGETNEARESTENEMY = "Target Nearest Enemy",
    TARGETPREVIOUSENEMY = "Target Previous Enemy",
    TARGETSCANENEMY = "Target Scan Enemy (Hold)",
    TARGETNEARESTFRIEND = "Target Nearest Friend",
    TARGETPREVIOUSFRIEND = "Target Previous Friend",
    TARGETNEARESTENEMYPLAYER = "Target Nearest Enemy Player",
    TARGETPREVIOUSENEMYPLAYER = "Target Previous Enemy Player",
    TARGETNEARESTFRIENDPLAYER = "Target Nearest Friendly Player",
    TARGETPREVIOUSFRIENDPLAYER = "Target Previous Friendly Player", 
    TARGETSELF = "Target Self",
    TARGETPARTYMEMBER1 = "Target Party Member 1",
    TARGETPARTYMEMBER2 = "Target Party Member 2",
    TARGETPARTYMEMBER3 = "Target Party Member 3",
    TARGETPARTYMEMBER4 = "Target Party Member 4",
    TARGETPET = "Target Pet",
    TARGETPARTYPET1 = "Target Party Pet 1",
    TARGETPARTYPET2 = "Target Party Pet 2",
    TARGETPARTYPET3 = "Target Party Pet 3",
    TARGETPARTYPET4 = "Target Party Pet 4",
    TARGETLASTHOSTILE = "Target Last Hostile",
    TARGETLASTTARGET = "Target Last Target",
    TARGETARENA1 = "Target Arena Enemy 1",
    TARGETARENA2 = "Target Arena Enemy 2",
    TARGETARENA3 = "Target Arena Enemy 3",
    TARGETARENA4 = "Target Arena Enemy 4",
    TARGETARENA5 = "Target Arena Enemy 5",
    FOCUSARENA1 = "Focus Arena Enemy 1",
    FOCUSARENA2 = "Focus Arena Enemy 2",
    FOCUSARENA3 = "Focus Arena Enemy 3",
    FOCUSARENA4 = "Focus Arena Enemy 4",
    FOCUSARENA5 = "Focus Arena Enemy 5",
    NAMEPLATES = "Show Enemy Nameplates",
    FRIENDNAMEPLATES = "Show Friendly Nameplates",
    ALLNAMEPLATES = "Show All Nameplates",
    INTERACTMOUSEOVER = "Interact With Mouseover",
    INTERACTTARGET = "Interact With Target",
    ASSISTTARGET = "Assist Target",
    ATTACKTARGET = "Attack Target",
    STARTATTACK = "Start Attack",
    PETATTACK = "Pet Attack",
    FOCUSTARGET = "Focus Target",
    TARGETFOCUS = "Target Focus",
    TARGETMOUSEOVER = "Target Mouseover",
    TARGETTALKER = "Target Current Talker",

--Target Markers
    RAIDTARGET1 = "Assign Star to Target",
    RAIDTARGET2 = "Assign Circle to Target",
    RAIDTARGET3 = "Assign Diamond to Target",
    RAIDTARGET4 = "Assign Triangle to Target",
    RAIDTARGET5 = "Assign Moon to Target",
    RAIDTARGET6 = "Assign Square to Target",
    RAIDTARGET7 = "Assign Cross to Target",
    RAIDTARGET8 = "Assign Skull to Target",
    RAIDTARGETNONE = "Clear Target Marker Icon",

--Vehicle Controls
    VEHICLEEXIT = "Exit Vehicle",
    VEHICLEPREVSEAT = "Previous Seat",
    VEHICLENEXTSEAT = "Next Seat",
    VEHICLEAIMUP = "Aim Up",
    VEHICLEAIMDOWN = "Aim Down",
    VEHICLEAIMINCREMENT = "Aim Increment",
    VEHICLEAIMDECREMENT = "Aim Decrement",

--Camera
    NEXTVIEW = "Next View",
    PREVVIEW = "Previous View",
    CAMERAZOOMIN = "Zoom In",
    CAMERAZOOMOUT = "Zoom Out",
    SETVIEW1 = "Set View 1",
    SETVIEW2 = "Set View 2",
    SETVIEW3 = "Set View 3",
    SETVIEW4 = "Set View 4",
    SETVIEW5 = "Set View 5",
    SAVEVIEW1 = "Save View 1",
    SAVEVIEW2 = "Save View 2",
    SAVEVIEW3 = "Save View 3",
    SAVEVIEW4 = "Save View 4",
    SAVEVIEW5 = "Save View 5",
    RESETVIEW1 = "Reset View 1",
    RESETVIEW2 = "Reset View 2",
    RESETVIEW3 = "Reset View 3",
    RESETVIEW4 = "Reset View 4",
    RESETVIEW5 = "Reset View 5",
    FLIPCAMERAYAW = "Flip Camera",
    CENTERCAMERA = "Center Camera",

--Ping System
    TOGGLEPINGLISTENER = "Ping",
    PINGATTACK = "Attack",
    PINGWARNING = "Warning",
    PINGONMYWAY = "On My Way",
    PINGASSIST = "Assist",

--Miscellaneous
    STOPCASTING = "Stop Casting",
    STOPATTACK = "Stop Attacking",
    DISMOUNT = "Dismount",
    MINIMAPZOOMIN = "Minimap Zoom In",
    MINIMAPZOOMOUT = "Minimap Zoom Out",
    TOGGLEMUSIC = "Toggle Music",
    TOGGLESOUND = "Toggle Sound",
    MASTERVOLUMEUP = "Master Volume Up",
    MASTERVOLUMEDOWN = "Master Volume Down",
    TOGGLEUI = "Toggle User Interface",
    TOGGLEFPS = "Toggle Framerate Display",
    SCREENSHOT = "Screen Shot",
    ITEMCOMPARISONCYCLING = "Item Comparison Cycling",
    TOGGLEGRAPHICSSETTINGS = "Toggle Graphics Settings",
    TOGGLESELFHIGHLIGHT = "Toggle Self Highlight",
    TOGGLEWINDOWED = "Toggle Windowed Mode",
}

InterfaceMapping = {

    ["Movement Keys"] = {
        {"Move and Steer", "MOVEANDSTEER"},
        {"Move Forward", "MOVEFORWARD"},
        {"Move Backward", "MOVEBACKWARD"},
        {"Turn Left", "TURNLEFT"},
        {"Turn Right", "TURNRIGHT"},
        {"Strafe Left", "STRAFELEFT"},
        {"Strafe Right", "STRAFERIGHT"},
        {"Jump", "JUMP"},
        {"Sit/Move Down", "SITORSTAND"},
        {"Sheath/Unsheath Weapon", "TOGGLESHEATH"},
        {"Toggle Autorun", "TOGGLEAUTORUN"},
        {"Start Autorun", "STARTAUTORUN"},
        {"Stop Autorun", "STOPAUTORUN"},
        {"Pitch Up", "PITCHUP"},
        {"Pitch Down", "PITCHDOWN"},
        {"Toggle Run/Walk", "TOGGLERUN"},
        {"Follow Target", "FOLLOWTARGET"},
    },

    ["Action Bar"] = {
        {"Action Button 1", "ACTIONBUTTON1"},
        {"Action Button 2", "ACTIONBUTTON2"},
        {"Action Button 3", "ACTIONBUTTON3"},
        {"Action Button 4", "ACTIONBUTTON4"},
        {"Action Button 5", "ACTIONBUTTON5"},
        {"Action Button 6", "ACTIONBUTTON6"},
        {"Action Button 7", "ACTIONBUTTON7"},
        {"Action Button 8", "ACTIONBUTTON8"},
        {"Action Button 9", "ACTIONBUTTON9"},
        {"Action Button 10", "ACTIONBUTTON10"},
        {"Action Button 11", "ACTIONBUTTON11"},
        {"Action Button 12", "ACTIONBUTTON12"},
        {"Extra Action Button 1", "EXTRAACTIONBUTTON1"},
        {"Pet Action Button 1", "BONUSACTIONBUTTON1"},
        {"Pet Action Button 2", "BONUSACTIONBUTTON2"},
        {"Pet Action Button 3", "BONUSACTIONBUTTON3"},
        {"Pet Action Button 4", "BONUSACTIONBUTTON4"},
        {"Pet Action Button 5", "BONUSACTIONBUTTON5"},
        {"Pet Action Button 6", "BONUSACTIONBUTTON6"},
        {"Pet Action Button 7", "BONUSACTIONBUTTON7"},
        {"Pet Action Button 8", "BONUSACTIONBUTTON8"},
        {"Pet Action Button 9", "BONUSACTIONBUTTON9"},
        {"Pet Action Button 10", "BONUSACTIONBUTTON10"},
        {"Action Page 1", "ACTIONPAGE1"},
        {"Action Page 2", "ACTIONPAGE2"},
        {"Action Page 3", "ACTIONPAGE3"},
        {"Action Page 4", "ACTIONPAGE4"},
        {"Action Page 5", "ACTIONPAGE5"},
        {"Action Page 6", "ACTIONPAGE6"},
        {"Previous Action Bar", "PREVIOUSACTIONPAGE"},
        {"Next Action Bar", "NEXTACTIONPAGE"},
        {"Toggle Action Bar Lock", "TOGGLEACTIONBARLOCK"},
        {"Toggle Self Cast", "TOGGLEAUTOSELFCAST"},
        {"Special Action Button 1", "SHAPESHIFTBUTTON1"},
        {"Special Action Button 2", "SHAPESHIFTBUTTON2"},
        {"Special Action Button 3", "SHAPESHIFTBUTTON3"},
        {"Special Action Button 4", "SHAPESHIFTBUTTON4"},
        {"Special Action Button 5", "SHAPESHIFTBUTTON5"},
        {"Special Action Button 6", "SHAPESHIFTBUTTON6"},
        {"Special Action Button 7", "SHAPESHIFTBUTTON7"},
        {"Special Action Button 8", "SHAPESHIFTBUTTON8"},
        {"Special Action Button 9", "SHAPESHIFTBUTTON9"},
        {"Special Action Button 10", "SHAPESHIFTBUTTON10"},
    },

    ["Action Bar 2"] = {
        {"Action Bar 2 Button 1", "MULTIACTIONBAR1BUTTON1"},
        {"Action Bar 2 Button 2", "MULTIACTIONBAR1BUTTON2"},
        {"Action Bar 2 Button 3", "MULTIACTIONBAR1BUTTON3"},
        {"Action Bar 2 Button 4", "MULTIACTIONBAR1BUTTON4"},
        {"Action Bar 2 Button 5", "MULTIACTIONBAR1BUTTON5"},
        {"Action Bar 2 Button 6", "MULTIACTIONBAR1BUTTON6"},
        {"Action Bar 2 Button 7", "MULTIACTIONBAR1BUTTON7"},
        {"Action Bar 2 Button 8", "MULTIACTIONBAR1BUTTON8"},
        {"Action Bar 2 Button 9", "MULTIACTIONBAR1BUTTON9"},
        {"Action Bar 2 Button 10", "MULTIACTIONBAR1BUTTON10"},
        {"Action Bar 2 Button 11", "MULTIACTIONBAR1BUTTON11"},
        {"Action Bar 2 Button 12", "MULTIACTIONBAR1BUTTON12"},
    },

    ["Action Bar 3"] = {
        {"Action Bar 3 Button 1", "MULTIACTIONBAR2BUTTON1"},
        {"Action Bar 3 Button 2", "MULTIACTIONBAR2BUTTON2"},
        {"Action Bar 3 Button 3", "MULTIACTIONBAR2BUTTON3"},
        {"Action Bar 3 Button 4", "MULTIACTIONBAR2BUTTON4"},
        {"Action Bar 3 Button 5", "MULTIACTIONBAR2BUTTON5"},
        {"Action Bar 3 Button 6", "MULTIACTIONBAR2BUTTON6"},
        {"Action Bar 3 Button 7", "MULTIACTIONBAR2BUTTON7"},
        {"Action Bar 3 Button 8", "MULTIACTIONBAR2BUTTON8"},
        {"Action Bar 3 Button 9", "MULTIACTIONBAR2BUTTON9"},
        {"Action Bar 3 Button 10", "MULTIACTIONBAR2BUTTON10"},
        {"Action Bar 3 Button 11", "MULTIACTIONBAR2BUTTON11"},
        {"Action Bar 3 Button 12", "MULTIACTIONBAR2BUTTON12"},
    },

    ["Action Bar 4"] = {
        {"Action Bar 4 Button 1", "MULTIACTIONBAR3BUTTON1"},
        {"Action Bar 4 Button 2", "MULTIACTIONBAR3BUTTON2"},
        {"Action Bar 4 Button 3", "MULTIACTIONBAR3BUTTON3"},
        {"Action Bar 4 Button 4", "MULTIACTIONBAR3BUTTON4"},
        {"Action Bar 4 Button 5", "MULTIACTIONBAR3BUTTON5"},
        {"Action Bar 4 Button 6", "MULTIACTIONBAR3BUTTON6"},
        {"Action Bar 4 Button 7", "MULTIACTIONBAR3BUTTON7"},
        {"Action Bar 4 Button 8", "MULTIACTIONBAR3BUTTON8"},
        {"Action Bar 4 Button 9", "MULTIACTIONBAR3BUTTON9"},
        {"Action Bar 4 Button 10", "MULTIACTIONBAR3BUTTON10"},
        {"Action Bar 4 Button 11", "MULTIACTIONBAR3BUTTON11"},
        {"Action Bar 4 Button 12", "MULTIACTIONBAR3BUTTON12"},
    },

    ["Action Bar 5"] = {
        {"Action Bar 5 Button 1", "MULTIACTIONBAR4BUTTON1"},
        {"Action Bar 5 Button 2", "MULTIACTIONBAR4BUTTON2"},
        {"Action Bar 5 Button 3", "MULTIACTIONBAR4BUTTON3"},
        {"Action Bar 5 Button 4", "MULTIACTIONBAR4BUTTON4"},
        {"Action Bar 5 Button 5", "MULTIACTIONBAR4BUTTON5"},
        {"Action Bar 5 Button 6", "MULTIACTIONBAR4BUTTON6"},
        {"Action Bar 5 Button 7", "MULTIACTIONBAR4BUTTON7"},
        {"Action Bar 5 Button 8", "MULTIACTIONBAR4BUTTON8"},
        {"Action Bar 5 Button 9", "MULTIACTIONBAR4BUTTON9"},
        {"Action Bar 5 Button 10", "MULTIACTIONBAR4BUTTON10"},
        {"Action Bar 5 Button 11", "MULTIACTIONBAR4BUTTON11"},
        {"Action Bar 5 Button 12", "MULTIACTIONBAR4BUTTON12"},
    },

    ["Action Bar 6"] = {
        {"Action Bar 6 Button 1", "MULTIACTIONBAR5BUTTON1"},
        {"Action Bar 6 Button 2", "MULTIACTIONBAR5BUTTON2"},
        {"Action Bar 6 Button 3", "MULTIACTIONBAR5BUTTON3"},
        {"Action Bar 6 Button 4", "MULTIACTIONBAR5BUTTON4"},
        {"Action Bar 6 Button 5", "MULTIACTIONBAR5BUTTON5"},
        {"Action Bar 6 Button 6", "MULTIACTIONBAR5BUTTON6"},
        {"Action Bar 6 Button 7", "MULTIACTIONBAR5BUTTON7"},
        {"Action Bar 6 Button 8", "MULTIACTIONBAR5BUTTON8"},
        {"Action Bar 6 Button 9", "MULTIACTIONBAR5BUTTON9"},
        {"Action Bar 6 Button 10", "MULTIACTIONBAR5BUTTON10"},
        {"Action Bar 6 Button 11", "MULTIACTIONBAR5BUTTON11"},
        {"Action Bar 6 Button 12", "MULTIACTIONBAR5BUTTON12"},
    },

    ["Action Bar 7"] = {
        {"Action Bar 7 Button 1", "MULTIACTIONBAR6BUTTON1"},
        {"Action Bar 7 Button 2", "MULTIACTIONBAR6BUTTON2"},
        {"Action Bar 7 Button 3", "MULTIACTIONBAR6BUTTON3"},
        {"Action Bar 7 Button 4", "MULTIACTIONBAR6BUTTON4"},
        {"Action Bar 7 Button 5", "MULTIACTIONBAR6BUTTON5"},
        {"Action Bar 7 Button 6", "MULTIACTIONBAR6BUTTON6"},
        {"Action Bar 7 Button 7", "MULTIACTIONBAR6BUTTON7"},
        {"Action Bar 7 Button 8", "MULTIACTIONBAR6BUTTON8"},
        {"Action Bar 7 Button 9", "MULTIACTIONBAR6BUTTON9"},
        {"Action Bar 7 Button 10", "MULTIACTIONBAR6BUTTON10"},
        {"Action Bar 7 Button 11", "MULTIACTIONBAR6BUTTON11"},
        {"Action Bar 7 Button 12", "MULTIACTIONBAR6BUTTON12"},
    },

    ["Action Bar 8"] = {
        {"Action Bar 8 Button 1", "MULTIACTIONBAR7BUTTON1"},
        {"Action Bar 8 Button 2", "MULTIACTIONBAR7BUTTON2"},
        {"Action Bar 8 Button 3", "MULTIACTIONBAR7BUTTON3"},
        {"Action Bar 8 Button 4", "MULTIACTIONBAR7BUTTON4"},
        {"Action Bar 8 Button 5", "MULTIACTIONBAR7BUTTON5"},
        {"Action Bar 8 Button 6", "MULTIACTIONBAR7BUTTON6"},
        {"Action Bar 8 Button 7", "MULTIACTIONBAR7BUTTON7"},
        {"Action Bar 8 Button 8", "MULTIACTIONBAR7BUTTON8"},
        {"Action Bar 8 Button 9", "MULTIACTIONBAR7BUTTON9"},
        {"Action Bar 8 Button 10", "MULTIACTIONBAR7BUTTON10"},
        {"Action Bar 8 Button 11", "MULTIACTIONBAR7BUTTON11"},
        {"Action Bar 8 Button 12", "MULTIACTIONBAR7BUTTON12"},
    },

    ["Interface Panel"] = {
        {"Toggle Game Menu", "TOGGLEGAMEMENU"},
        {"Toggle Backpack", "TOGGLEBACKPACK"},
        {"Toggle Reagent Bag", "TOGGLEREAGENTBAG1"},
        {"Toggle Bag 1", "TOGGLEBAG1"},
        {"Toggle Bag 2", "TOGGLEBAG2"},
        {"Toggle Bag 3", "TOGGLEBAG3"},
        {"Toggle Bag 4", "TOGGLEBAG4"},
        {"Open All Bags", "OPENALLBAGS"},
        {"Toggle Character Pane", "TOGGLECHARACTER0"},
        {"Toggle Reputation Pane", "TOGGLECHARACTER2"},
        {"Toggle Currency Frame", "TOGGLECURRENCY"},
        {"Toggle Spellbook", "TOGGLESPELLBOOK"},
        {"Toggle Profession Book", "TOGGLEPROFESSIONBOOK"},
        {"Toggle Pet Book", "TOGGLEPETBOOK"},
        {"Toggle Talent Pane", "TOGGLETALENTS"},
        {"Toggle Achievement Frame", "TOGGLEACHIEVEMENT"},
        {"Toggle Statistics Frame", "TOGGLESTATISTICS"},
        {"Toggle Quest Log", "TOGGLEQUESTLOG"},
        {"Toggle World Map Pane", "TOGGLEWORLDMAP"},
        {"Toggle World Map Size", "TOGGLEWORLDMAPSIZE"},
        {"Toggle Minimap", "TOGGLEMINIMAP"},
        {"Toggle Zone Map", "TOGGLEBATTLEFIELDMINIMAP"},
        {"Toggle Score Screen", "TOGGLEWORLDSTATESCORES"},
        {"Toggle Guild Pane", "TOGGLEGUILDTAB"},
        {"Toggle Social Pane", "TOGGLESOCIAL"},
        {"Toggle Friends Pane", "TOGGLEFRIENDSTAB"},
        {"Toggle Quick Join", "TOGGLEQUICKJOINTAB"},
        {"Toggle Who Pane", "TOGGLEWHOTAB"},
        {"Toggle Chat Pane", "TOGGLECHATTAB"},
        {"Toggle Raid Pane", "TOGGLERAIDTAB"},
        {"Toggle Text To Speech Config", "TOGGLETEXTTOSPEECH"},
        {"Toggle Group Finder", "TOGGLEGROUPFINDER"},
        {"Toggle Dungeons & Raids", "TOGGLEDUNGEONSANDRAIDS"},
        {"Toggle PVP Pane", "TOGGLECHARACTER4"},
        {"Toggle Collections", "TOGGLECOLLECTIONS"},
        {"Toggle Mount Journal", "TOGGLECOLLECTIONSMOUNTJOURNAL"},
        {"Toggle Pet Journal", "TOGGLECOLLECTIONSPETJOURNAL"},
        {"Toggle Toy Box", "TOGGLECOLLECTIONSTOYBOX"},
        {"Toggle Heirlooms Pane", "TOGGLECOLLECTIONSHEIRLOOM"},
        {"Toggle Appearances", "TOGGLECOLLECTIONSWARDROBE"},
        {"Toggle Adventure Guide", "TOGGLEENCOUNTERJOURNAL"},
        {"Toggle Garrison Report", "TOGGLEGARRISONLANDINGPAGE"},
    },

    ["Chat"] = {
        {"Open Chat", "OPENCHAT"},
        {"Open Chat Slash", "OPENCHATSLASH"},
        {"Chat Page Up", "CHATPAGEUP"},
        {"Chat Page Down", "CHATPAGEDOWN"},
        {"Chat Bottom", "CHATBOTTOM"},
        {"Chat Reply", "REPLY"},
        {"Re-Whisper", "REPLY2"},
        {"Combat Log Page Up", "COMBATLOGPAGEUP"},
        {"Combat Log Page Down", "COMBATLOGPAGEDOWN"},
        {"Combat Log Bottom", "COMBATLOGBOTTOM"},
        {"Toggle Combat Log", "TOGGLECOMBATLOG"},
        {"Voice Chat: Toggle Mute Self", "TOGGLE_VOICE_SELF_MUTE"},
        {"Voice Chat: Toggle Deafen Self", "TOGGLE_VOICE_SELF_DEAFEN"},
        {"Stop Text To Speech Playback", "TEXT_TO_SPEECH_STOP"},
    },

    ["Targeting"] = {
        {"Target Nearest Enemy", "TARGETNEARESTENEMY"},
        {"Target Previous Enemy", "TARGETPREVIOUSENEMY"},
        {"Target Scan Enemy (Hold)", "TARGETSCANENEMY"},
        {"Target Nearest Friend", "TARGETNEARESTFRIEND"},
        {"Target Previous Friend", "TARGETPREVIOUSFRIEND"},
        {"Target Nearest Enemy Player", "TARGETNEARESTENEMYPLAYER"},
        {"Target Previous Enemy Player", "TARGETPREVIOUSENEMYPLAYER"},
        {"Target Nearest Friendly Player", "TARGETNEARESTFRIENDPLAYER"},
        {"Target Previous Friendly Player", "TARGETPREVIOUSFRIENDPLAYER"},
        {"Target Self", "TARGETSELF"},
        {"Target Party Member 1", "TARGETPARTYMEMBER1"},
        {"Target Party Member 2", "TARGETPARTYMEMBER2"},
        {"Target Party Member 3", "TARGETPARTYMEMBER3"},
        {"Target Party Member 4", "TARGETPARTYMEMBER4"},
        {"Target Pet", "TARGETPET"},
        {"Target Party Pet 1", "TARGETPARTYPET1"},
        {"Target Party Pet 2", "TARGETPARTYPET2"},
        {"Target Party Pet 3", "TARGETPARTYPET3"},
        {"Target Party Pet 4", "TARGETPARTYPET4"},
        {"Target Last Hostile", "TARGETLASTHOSTILE"},
        {"Target Last Target", "TARGETLASTTARGET"},
        {"Target Arena Enemy 1", "TARGETARENA1"},
        {"Target Arena Enemy 2", "TARGETARENA2"},
        {"Target Arena Enemy 3", "TARGETARENA3"},
        {"Target Arena Enemy 4", "TARGETARENA4"},
        {"Target Arena Enemy 5", "TARGETARENA5"},
        {"Focus Arena Enemy 1", "FOCUSARENA1"},
        {"Focus Arena Enemy 2", "FOCUSARENA2"},
        {"Focus Arena Enemy 3", "FOCUSARENA3"},
        {"Focus Arena Enemy 4", "FOCUSARENA4"},
        {"Focus Arena Enemy 5", "FOCUSARENA5"},
        {"Show Enemy Nameplates", "NAMEPLATES"},
        {"Show Friendly Nameplates", "FRIENDNAMEPLATES"},
        {"Show All Nameplates", "ALLNAMEPLATES"},
        {"Interact With Mouseover", "INTERACTMOUSEOVER"},
        {"Interact With Target", "INTERACTTARGET"},
        {"Assist Target", "ASSISTTARGET"},
        {"Attack Target", "ATTACKTARGET"},
        {"Start Attack", "STARTATTACK"},
        {"Pet Attack", "PETATTACK"},
        {"Focus Target", "FOCUSTARGET"},
        {"Target Focus", "TARGETFOCUS"},
        {"Target Mouseover", "TARGETMOUSEOVER"},
        {"Target Current Talker", "TARGETTALKER"},
    },

    ["Target Markers"] = {
        {"Assign Star to Target", "RAIDTARGET1"},
        {"Assign Circle to Target", "RAIDTARGET2"},
        {"Assign Diamond to Target", "RAIDTARGET3"},
        {"Assign Triangle to Target", "RAIDTARGET4"},
        {"Assign Moon to Target", "RAIDTARGET5"},
        {"Assign Square to Target", "RAIDTARGET6"},
        {"Assign Cross to Target", "RAIDTARGET7"},
        {"Clear Target Marker Icon", "RAIDTARGETNONE"},
    },

    ["Vehicle Controls"] = {
        {"Exit Vehicle", "VEHICLEEXIT"},
        {"Previous Seat", "VEHICLEPREVSEAT"},
        {"Next Seat", "VEHICLENEXTSEAT"},
        {"Aim Up", "VEHICLEAIMUP"},
        {"Aim Down", "VEHICLEAIMDOWN"},
        {"Aim Increment", "VEHICLEAIMINCREMENT"},
        {"Aim Decrement", "VEHICLEAIMDECREMENT"},
    },

    ["Camera"] = {
        {"Next View", "NEXTVIEW"},
        {"Previous View", "PREVVIEW"},
        {"Zoom In", "CAMERAZOOMIN"},
        {"Zoom Out", "CAMERAZOOMOUT"},
        {"Set View 1", "SETVIEW1"},
        {"Set View 2", "SETVIEW2"},
        {"Set View 3", "SETVIEW3"},
        {"Set View 4", "SETVIEW4"},
        {"Set View 5", "SETVIEW5"},
        {"Save View 1", "SAVEVIEW1"},
        {"Save View 2", "SAVEVIEW2"},
        {"Save View 3", "SAVEVIEW3"},
        {"Save View 4", "SAVEVIEW4"},
        {"Save View 5", "SAVEVIEW5"},
        {"Reset View 1", "RESETVIEW1"},
        {"Reset View 2", "RESETVIEW2"},
        {"Reset View 3", "RESETVIEW3"},
        {"Reset View 4", "RESETVIEW4"},
        {"Reset View 5", "RESETVIEW5"},
        {"Flip Camera", "FLIPCAMERAYAW"},
        {"Center Camera", "CENTERCAMERA"},
    },

    ["Ping System"] = {
        {"Ping", "TOGGLEPINGLISTENER"},
        {"Attack", "PINGATTACK"},
        {"Warning", "PINGWARNING"},
        {"On My Way", "PINGONMYWAY"},
        {"Assist", "PINGASSIST"},
    },

    ["Miscellaneous"] = {
        {"Stop Casting", "STOPCASTING"},
        {"Stop Attacking", "STOPATTACK"},
        {"Dismount", "DISMOUNT"},
        {"Minimap Zoom In", "MINIMAPZOOMIN"},
        {"Minimap Zoom Out", "MINIMAPZOOMOUT"},
        {"Toggle Music", "TOGGLEMUSIC"},
        {"Toggle Sound", "TOGGLESOUND"},
        {"Master Volume Up", "MASTERVOLUMEUP"},
        {"Master Volume Down", "MASTERVOLUMEDOWN"},
        {"Toggle User Interface", "TOGGLEUI"},
        {"Toggle Framerate Display", "TOGGLEFPS"},
        {"Screen Shot", "SCREENSHOT"},
        {"Item Comparison Cycling", "ITEMCOMPARISONCYCLING"},
        {"Toggle Graphics Settings", "TOGGLEGRAPHICSSETTINGS"},
        {"Toggle Self Highlight", "TOGGLESELFHIGHLIGHT"},
        {"Toggle Windowed Mode", "TOGGLEWINDOWED"},
    },
}